.gitmodules
allows "submodule update --remote" to refresh to current version
=> Set buildroot branch name

patches/arm-trusted-firmware/v2.7/binutils-2.39.patch
Adopted from https://review.trustedfirmware.org/c/TF-A/trusted-firmware-a/+/19401/4/Makefile
=> Patch for building ARM TF-A with binutils-2.39+

package/sysrepo-plugin-system/sysrepo-plugin-system.mk, src/confd/src/ietf-system.c, src/confd/yang/infix-system@2014-08-06.yang
Not sure if this is even something we want? I did it mainly to learn and to test the work flow.
If this is indeed something we want then I intent to fix the duplication of the default value (in skel /etc/motd and in the confd C code).
I might also hook it into the `aug` framework, even tho it should never fail (TM) and "abort" seems to work as intended?
Add the ability to set and delete system MotD (Message Of The Day) using the cli.
So there's no staging concept (aug), if user issues "leave" the change takes immediate effect.
The default value is hard coded in two places, confd and the rootfs file /etc/motd. The intention is to fix this in upcoming patches.
Introduces:
exec> configure> set system motd STRING
exec> configure> delete system motd
=> src/confd: add the ability to change MotD in cli

.github/workflows/build.yml
Since complete builds currently take over 2h to complete, we cannot start the existing build workflow on any event.
This PR locks down our current GitHub action in two ways:
- Only allow (or attempt) upload of [latest build](https://github.com/kernelkit/infix/releases/tag/latest) from main repo and main branch
- Start _Bob the Builder_ automatically on manual start (`workflow_dispatch`) or when a PR to main has been approved
> Separate workflows for validating YANG models and running unit tests to be added later.
=> Lock down actions

src/confd/src/Makefile.am, src/confd/src/core.h, src/confd/src/ietf-system.c, src/confd/src/systemv.c, src/confd/src/systemv.h
This PR introduces the ability to:
* Create or delete a UNIX user.
* Set or delete a UNIX user password.
The password needs to be hashed and in a UNIX shadow format, such as
`$ALG$SALT$HASH`. We want to avoid the handling of clear text
passwords as much as possible. In the meanwhile, passwords
can be generated in the infix shell using `mkpasswd`.
`configure> set system authentication user foo`
`configure> delete system authentication user foo`
`configure> set system authentication user foo password ...`
This PR also exposes and uses existing "systemv" functions.
=> Add basic user authentication to ietf system

src/confd/src/core.c, src/confd/src/core.h
Refactor `register_change()` wrapper, for `sr_module_change_subscribe()`, with an additional twist of setting up a commit DONE event catcher.
This creates a global event hook that ensures we call `initctl reload` after all module callbacks have completed, regardless of the xpath and without having to have "shadow" subscriptions to all new modules being added to confd.
Based on on ideas from https://github.com/sysrepo/sysrepo/issues/2188
=> confd: add global event hook support

board/common/rootfs/lib/infix/cfg-bootstrap, board/netconf/rootfs/etc/auto-factory.d/10-authentication.json
Add a user `admin` with password `admin` to the generated factory config.
This is a work in progress. A user can login using these credentials but there's still some work needed for NETCONF functionality. In the meantime, developers can continue using `root`.
The goal here is to disable the password for `root`, thus disallowing "root" login and make root own all system processes.
=> Add admin user to factory config

board/common/rootfs/sbin/dagger, qemu/qemu.sh, src/confd/src/ietf-interfaces.c, src/confd/src/infix-dhcp.c, src/confd/src/lyx.c, src/confd/src/srx_val.c, src/confd/src/srx_val.h, src/confd/yang/ieee802-dot1q-types@2022-10-29.yang, src/confd/yang/ietf-if-extensions@2023-01-26.yang, src/confd/yang/ietf-if-vlan-encapsulation@2023-01-26.yang
Basic support for VLAN sub-interfaces:
```
interface eth0.10 {
type ethSubInterface;
encapsulation {
dot1q-vlan {
outer-tag {
tag-type s-vlan;
vlan-id 10;
}
}
}
parent-interface eth0;
ipv6 {
autoconf {
create-global-addresses true;
}
}
}
```
=> Add support for VLAN sub-interfaces

src/confd/src/confd/dagger.h, src/confd/src/confd/ietf-interfaces.c, src/confd/yang/infix-if-bridge@2023-05-31.yang, test/case/infix_interfaces/all.yaml, test/case/infix_interfaces/bridge_vlan.py
Example:
```
interface br0 {
type bridge;
enabled true;
bridge {
vlans {
pvid 4094;
vlan 10 {
untagged e2;
tagged br0;
}
}
}
}
```
=> Add NETCONF support for Linux bridge native VLANs

src/confd/src/confd/ietf-system.c, src/confd/src/lib/lyx.c, src/confd/src/lib/lyx.h, src/confd/src/statd/core.c
This might break something. **Please test your use case**.
I didn't find any need for the "first" concept at all. I have tested to query the operational status for both ietf-system (confd) and ietf-interfaces (statd). Sysrepo is still able to report operational status in the same manner as before and the memory leak is fixed.
Here's what I used to test this:
```sysrepocfg -X -d operational -m ietf-system```
```sysrepocfg -X -d operational -m ietf-interfaces```
Prior to this patch, every new call to lydx_new_path() where "first" was set to 1 resulted in a memory leak of 72 bytes. Typically at least once for each sysrepo query.
The memory was allocated deep down in the lyd library, but as the parent node wasn't set (NULL) it wasn't found by sysrepo when cleaning up.
**In this patch we …
=> confd: fix memory leak in lydx_new_path()

test/case/ietf_interfaces/all.yaml, test/case/ietf_interfaces/ipv4_address.py, test/infamy/netconf.py
Adding support for different NETCONF operations other than merge (default). 
Adding two new tests: 
- Setting IPv4 address on eth0
- Removing IPv4 addresses from eth0
=> Test env: Add netconf remove operation & new tests

patches/klish/0002-tinyrl-Support-changing-default-keybindings.patch
Extracted from kkit fix branch of kernelkit/klish.
=> klish: backport hotkey fixes, now Ctrl-D and Ctrl-Z work properly

test/case/ietf_system/add_delete_user.py, test/case/ietf_system/all.yaml
Added a test case for adding/deleting a user
=> test/case: Add authentication/user test

README.md
two fixes
- first a typo (probably copy/paste issue)
- the sleep and 'vtysh -b' was added to make vtysh read the /etc/frr/frr.conf file upon start(*) sleep needed to make this happen after initctl reload
(*) See https://docs.frrouting.org/en/latest/vtysh.html#integrated-configuration-mode But there ought to be a better way.
=> Doc: Fixing hybrid-mode FRR example

src/statd/statd.c
Add support for yang link state "lower-layer-down" and "not-present".
=> statd: add support for additional operstates

src/klinfix/src/klinfix.c, src/klinfix/xml/infix.xml
This patch set adds RPC commands to the CLI.  A generic function for RPCs is added, along with commands for reboot and poweroff, that replace the existing ones.  A `set datetime` command is also added, along with a `show datetime` that display output in the same format as the `set` command requires.
=> cli: rpc commands for reboot/poweroff and set datetime

src/confd/src/confd/core.c, src/confd/src/confd/ietf-interfaces.c, src/confd/src/confd/infix-system-software.c, src/confd/src/lib/common.h, src/confd/src/lib/helpers.c, src/statd/Makefile, src/statd/statd.c
~~Fix a problem with statd not properly mapping all kernel operstates to proper yang `oper-status` names.  E.g., `LOWERLAYERDOWN` should map top `lower-layer-down`.~~ <-- (Fixed in #92)
~~Also includes a~~ A mix of minor fixes and cleanup to both statd and confd, mostly focused on `DEBUG()` macros.
=> statd,confd: misc. fixes with improved debug support

src/confd/src/confd/ietf-interfaces.c
This is a proposal to fix the issue of loopback having operstate UNKNOWN, which otherwise propagates over NETCONF as well.
See separate discussion thread in Projects.
=> linux: add loopback carrier for operstate up

src/statd/statd.c
An iana or infix interface type is derived from "ip link" data. Such as loopback -> iana-if-type:softwareLoopback.
This patch adds support for the following types:
loopback, ethernetCsmacd, veth, l2vlan and bridge.
Example data:
```
{
"ietf-interfaces:interfaces": {
"interface": [
{
"name": "lo",
"type": "iana-if-type:softwareLoopback",
"oper-status": "unknown",
"if-index": 1
},
{
"name": "e0",
"type": "iana-if-type:ethernetCsmacd",
"oper-status": "up",
"if-index": 2
},
{
"name": "e0.100",
"type": "iana-if-type:l2vlan",
"oper-status": "down",
"if-index": 3
},
{
"name": "br0",
"type": "iana-if-type:bridge",
"oper-status": "down",
"if-index": 4
},
{
"name": "veth1",
"type": "infix-if-type:veth",
"oper-status": "down",
"if-index": 5
}
]
}
}
```
=> statd: add interface type to operational data

board/common/qemu/qemu.sh, test/case/infix_interfaces/all.yaml, test/case/infix_interfaces/bridge_fwd_dual_dut.py, test/case/infix_interfaces/bridge_fwd_sgl_dut.py, test/case/infix_interfaces/bridge_vlan_separation.py, test/infamy/netns.py, test/infamy/topologies/1x1.dot, test/infamy/topologies/1x2.dot, test/infamy/topologies/1x3.dot, test/infamy/topologies/2x4.dot, test/infamy/topology.py, test/virt/dual/topology.dot.in
Edge(port) type parameter added to the topology files (**test/infamy** commit) in order to avoid false mgmt port selection.
There is a possibility for a test program to try to configure (set) a management port of a node to the one already allocated to a bridge in the previous test case. To avoid this, port mapping process in topology.py matches the edge type in the physical and the logical topology prior to the mapping of the other ports (bridge ports in this case)
=> Bridge vlan forwarding

doc/container.md, doc/developers-guide.md, doc/virtual.md
Fixing some broken links.
Regarding the url to the CLI guide in container.md, changing it to cli/README.md
(rather than cli/introduction.md) is perhaps better.  Or to "cli/"!
I have a problem to display https://github.com/jovatn/infix-jovatn/tree/main/doc/cli/README.md
but with https://github.com/jovatn/infix-jovatn/tree/main/doc/cli it works good
=> Fixing broken urls in document docs

board/netconf/rootfs/lib/infix/cli-pretty
Re-add statistics to the detailed show interface view.
Also, print empty columns for some values that the user adds/remove, such as ipv4 address.
This make it easier to spot if a interface has no ip set.
=> Add CLI interface statistics

board/common/rootfs/etc/iproute2/rt_addrprotos, board/common/rootfs/usr/share/udhcpc/default.script, board/netconf/rootfs/lib/infix/cli-pretty, patches/iproute2/ip-support-ip-address-protocol.patch, src/confd/src/ietf-interfaces.c, src/statd/statd.c, test/case/cli_pretty/json/bloated.json
This PR adds ip proto / origin info.
```
root@infix-00-00-00:/> show interfaces 
INTERFACE        PROTOCOL          STATE          DATA                          
e0               ethernet          UP             02:00:00:00:00:00             
ipv4                             192.168.1.1/24 (static)
ipv4                             198.10.1.162/24 (dhcp)
lo               ethernet          UP             00:00:00:00:00:00             
ipv4                             127.0.0.1/8 (static)
```
It does this by setting ip/kernel `proto` and converting it to YANG `origin`, which is exposed to the user.
**NOTE**
* The udhcpc default.script is modified in this PR, I have tested it manually and it works better than before (see commit msg). However, such modifications are error-prone and we need to …
=> add ip origin tracking

board/common/rootfs/etc/avahi/avahi-autoipd.action, board/common/rootfs/etc/iproute2/rt_addrprotos, board/netconf/rootfs/lib/infix/cli-pretty, src/statd/statd.c, test/case/cli_pretty/json/bloated.json
This PR adds basic IPv6 info to the operational datastore.
It also adds YANG origin for avahi IPv4 link-local addresses.
**CLI Example with avahi IPv4-LL and eui64 generated IPv6-LL**
```
INTERFACE       PROTOCOL   STATE       DATA                                     
e0              ethernet   UP          02:00:00:00:00:00                        
ipv4                   169.254.1.3/16 (random)
ipv4                   192.168.1.1/24 (static)
ipv6                   fe80::ff:fe00:0/64 (link-layer)
lo              ethernet   UP          00:00:00:00:00:00                        
ipv4                   127.0.0.1/8 (static)
ipv6                   ::1/128 (static)
```
**CLI Example with avahi IPv4-LL and random/secure generated IPv6-LL**
```
INTERFACE       PROTOCOL   STATE       DATA …
```
=> Add IPv6 operational data

src/confd/confd-bootstrap.sh, src/confd/src/ietf-interfaces.c
- Enable privacy feature, allows true random address instead of EUI64
- Allow global addresses to use router prefix
Fixes #136
=> confd: fix IPv6 autoconf support

board/netconf/rootfs/lib/infix/cli-pretty, test/case/cli_pretty/json/bloated.json
Don't use iana-if-type, use infix-if-type.
Fixes #142
=> cli: use infix interfaces types in cli-pretty

src/confd/yang/infix-ip@2023-09-14.yang
MTU configuration/status not yet implemented in Infix, thus deviations added.
=> Add deviations for MTU configuration (IPv4/IPv6) in ietf-ip.yang

.github/workflows/regression.yml
Use the new fancy result-gh.md file which as github emojis.
Also,  split result publishing to its own run command to simplify the YAML file.
=> Use GitHub result file in regression test

src/statd/iface-ip-addr.c
Handle IPv6 Router Advertisement (RA) based addresses.
If the last 64 bits of a link-local address is generated using the local MAC address of the interface, i.e. a EUI-64 based address. Then the origin is set to "link-layer".
If the addrgenmode is set to "random" instead of "eui64", then the device will generate the interface identifier portion of the address (the last 64 bits) randomly rather than deriving it from the MAC address using the EUI-64 process. This will result in a "random" origin.
=> statd: handle IP origin for IPv6 RA

board/netconf/rootfs/lib/infix/cli-pretty, test/case/cli_pretty/json/bloated.json
Use known data from .self to avoid crashing if the oper-status is missing for a interface.
Fixes #162
=> cli: handle missing oper-status

src/confd/src/ietf-interfaces.c
The Marvell mv88e6xxx switch driver currently used in active projects do not support multicast router ports properly yet.  Considering that Infix do not yet have YANG support for configuring IGMP/MLD snooping, we have decided to disable it in bridge setups by default.
=> Disable bridge multicast snooping (IGMP/MLD) by default

package/confd/tmpfiles.conf, src/confd/bin/.confdrc, src/confd/bin/bootstrap, src/confd/bin/gen-interfaces, src/confd/bin/load, src/confd/confdrc
This PR fixes the annoying "RMA" issue we've seen over the past week or so.  Instead of saving `factory-config` and `failure-config` to `/cfg`, we now regenerate them on each boot to match our YANG models.  The files are stored in `/run/confd/`, except for `startup-config` that remains in `/cfg`.
It also address the "unsorted interfaces" issue we found in customer bridge created by `gen-interfaces` today.
=> Regen factory on every boot

board/netconf/rootfs/lib/infix/cli-pretty, doc/eth-counters.md, src/statd/iface-ethtool.c
Add counters from Ethtool groups to the operational data store. The mapping from Linux / Ethtool to YANG is described in the included document eth-counters.md.
=> statd: add more ethtool counters to op datastore

src/klish-plugin-infix/xml/infix.xml
Adhere to our recommendations and avoid pseudorandom passwords which are "easy to remember". Also increase password length to 13 chars.
Side notes:
Knowing that a password contains at least one char, one number and so on, lowers the number of possible passwords to test when brute forcing.
The entropy for the pwgen "easy to remember" passwords isn't good (naturally).
=> cli: use pwgen secure and increase password length

board/netconf/rootfs/lib/infix/cli-pretty, board/netconf/rootfs/lib/infix/ethtool-to-json, src/statd/iface-ethtool.c, test/case/cli_pretty/json/bloated.json
* Add the status of autoneg to the operational datastore.
* Print it in the detauled interface CLI view
Sysrepo data:
```
"ieee802-ethernet-interface:ethernet": {                                     
"auto-negotiation": {                                                      
"enable": false                                                          
}                                                                          
},   
```
CLI:
```
root@infix:/> show interfaces name p1
name                : p1
index               : 4
mtu                 : 1500
operational status  : up
auto-negotiation    : on
```
=> Add autoneg status to op datastore

board/netconf/rootfs/lib/infix/cli-pretty, src/klish-plugin-infix/xml/infix.xml
This affects CLI command such as:
> show interface name p1
Prior to this patch, this took roughly ~1200ms on hardware and with the patch it takes roughly 50ms.
=> cli: speedup detailed interface view

board/common/rootfs/bin/yorn, package/klish/klish.mk, src/klish-plugin-infix/xml/infix.xml
After the latest upgrade of Klish & C:o we experienced a few annoying regressions that this PR takes care of:
- `shell` command stalls
- `show interfaces` no longer shows line drawing chars
- Ctrl-C in `follow syslog` no longer works
All this, and more, have been addressed in this PR.
> **TODO:** I'd still like to get the initial probing of serial console to work better.  Klish works fine if logging in to bash/sh first and then starting `cli`, but if `/bin/clish` is the login shell it gets stuck at 80x25 (hard-coded defaults).
=> CLI regression fixes

src/confd/src/ietf-interfaces.c, src/confd/yang/infix-if-bridge@2023-11-08.yang
First, drop bridge vlans pvid from YANG model.  This enforces explicit port VLAN assignment, by setting `vlan_default_pvid = 0`.  Hence, untagged frames on tagged ports are now dropped by default.
Finally, fix VLAN filtering detection.  Until now the filtering was always enabled, but worked fine in tests because `vlan_default_pvid` defaulted to 1, because of the YANG model's `pvid` default value.  Instead we now check if the bridge has any VLANs configured, while there are none the bridge will be VLAN agnostic, when there is at least one we enable VLAN filtering and all bridge ports that are not a tagged or untagged member will have all its frames dropped on ingress.
=> Bridge VLAN filtering fixes

src/confd/bin/bootstrap, src/confd/yang/infix-ethernet-interface@2023-11-22.yang
- Add deviations for non-supported statistics
- Limit config, currently we only have ro support
- Add deviations for non-supported configs and status leafs
[skip ci]
=> Draft infix deviations for ieee802-ethernet-interfaces

board/netconf/rootfs/lib/infix/cli-pretty, board/netconf/rootfs/lib/infix/yanger, external.mk, src/.clang-format, src/confd/bin/bootstrap, src/confd/yang/infix-routing@2013-10-27.yang, src/confd/yang/infix-routing@2023-11-23.yang, src/klish-plugin-infix/xml/infix.xml, src/statd/statd.c, test/case/cli_pretty/all.yaml, test/case/cli_pretty/json/bloated.json
In the CLI:
admin@infix-00-00-00:/> show routes
```
PREFIX                        DESTINATION                   PROTOCOL  METRIC
1.1.1.0/24                    e0                            kernel
192.168.100.0/24              1.1.1.1                       static    20
192.168.110.2/32              blackhole                     static    20
192.168.120.2/32              blackhole                     static    20
192.168.130.2/32              unreachable                   static    20
```
EDIT by @rical : framed output in markdown ```
=> Add support for reading routing operational data for IPv4

README.md, doc/cli/introduction.md, doc/cli/tutorial.md, doc/networking.md, package/klish-plugin-sysrepo/klish-plugin-sysrepo.hash, package/klish-plugin-sysrepo/klish-plugin-sysrepo.mk, src/confd/yang/infix-ethernet-interface@2023-11-22.yang, src/klish-plugin-infix/xml/infix.xml
We've been annoyed by typing `edit interfaces interface e0` for a long time now, but with the addition of static routing I felt it was time to do something about it.  I started out playing with schema mounts, but since alias/subtree mounts and/or xpaths don't seem to be allowed atm. there does not seem much to be earned from going down that path[^1].  So instead I went for patching the klish-plugin-sysrepo code.
The insanity of having to type:
admin@example:/config/> edit routing control-plane-protocols control-plane-protocol static name default static-routes ipv4
admin@example:/config/routing/control-plane-protocols/control-plane-protocol/static/name/default/static-routes/ipv4/> set route 192.168.200.0/24 next-hop next-hop-address 192.168.1.1
has now been replaced with the slightly less …
=> Simplify CLI use by collapsing containers with only list elements

src/klish-plugin-infix/src/infix.c, src/klish-plugin-infix/xml/infix.xml
Tested working:
- `copy running-config startup-config`
- `copy running-config foo`  
=> `/cfg/foo.cfg`
- `copy factory-config running-config`
- `copy foo startup-config`
- `copy startup-config running-config`
- `copy startup-config tftp://192.168.122.1/upload/`
=> `/tftproot/upload/startup-config.cfg`
- `copy tftp://192.168.122.1/upload/startup-config.cfg foo`
- `copy tftp://192.168.122.1/upload/startup-config.cfg startup-config`
Fix #155
=> Allow copy to generic files (for backup) or to/from remote destination

package/confd/avahi.service, package/confd/confd.mk
Currently we only advertise SSH+SFTP services over mDNS-SD, which are the default services from the avahi package.  This patch adds support for _netconf-ssh._tcp as well.
=> package/confd: install avahi _netconf-ssh._tcp service record

src/confd/src/infix-system-software.c
As it turns out, references to module objects are not safe to keep across callbacks. In particular: loading a new model into sysrepo at runtime may cause it to move objects around in memory.
Therefore, fetch a valid reference to "infix-system" on every callback instead.
=> confd: Don't cache libyang module references

src/confd/yang/infix-if-bridge@2023-12-02.yang
```
admin@infix-00-00-00:/> configure
admin@infix-00-00-00:/config/> edit interface br0
admin@infix-00-00-00:/config/interface/br0/> set bridge-port bridge br0
admin@infix-00-00-00:/config/interface/br0/> leave
Error: Must refer to a bridge interface (and not itself).
Data location "/ietf-interfaces:interfaces/interface[name='br0']/infix-interfaces:bridge-port/bridge".
Failed committing candidate to running: Validation failed
admin@infix-00-00-00:/config/interface/br0/>
```
=> Fix #177: ensure bridge is not bridge port to itself

board/common/rootfs/etc/motd, board/netconf/rootfs/bin/clish, board/netconf/rootfs/etc/profile.d/cli-hint.sh, src/confd/bin/Makefile.am, src/confd/bin/bootstrap, src/confd/bin/gen-motd, src/klish-plugin-infix/xml/infix.xml
This opens up lots of scripting opportunities via ssh, without first having to install some NETCONF tools to change admin's shell. 
Some things you can now do:
- SCP works out-of-the-box now: `scp admin@[fe80::ff:fe00:0%qtap0]:/etc/motd /tmp/ix-motd`
- Config can be read/modified via SSH, using sysrepocfg: `ssh admin@fe80::ff:fe00:0%qtap0 sysrepocfg -X -fjson -d operational -x "/system/hostname"`
=> Change the default shell of the admin user to bash

doc/networking.md, package/klish-plugin-sysrepo/klish-plugin-sysrepo.hash, package/klish-plugin-sysrepo/klish-plugin-sysrepo.mk, src/confd/yang/infix-routing@2024-01-09.yang
* Update klish to fix the bug
* Update documentation (simplier configuration now)
* Add limitation (must expression) in yang to limit to supported routing protocols
=> Fix klish bug not adding prefix to identityrefs

board/aarch64/dts/alder/alder.dtsi
There is no Micro-SD slot on the alder board. Not even an optional one.
=> board/aarch64: alder: Remove Micro-SD support

board/netconf/rootfs/libexec/infix/yanger, src/confd/bin/gen-interfaces, src/confd/src/ietf-interfaces.c, src/confd/yang/infix-if-type@2023-08-21.yang, test/case/cli/cli-output/show-interface-br0.txt, test/case/cli/cli-output/show-interface-e2.txt, test/case/cli/cli-output/show-interface-e3.txt, test/case/cli/cli-output/show-interface-e4.txt, test/case/cli/system-output/ethtool-br0.txt, test/case/cli/system-output/ip-link-show-dev-e0.json, test/case/cli/system-output/ip-link-show-dev-e1.json, test/case/ietf_interfaces/iface_phys_address.py, test/case/ietf_interfaces/ipv4_address.py, test/case/ietf_interfaces/routing_basic.py, test/case/ietf_interfaces/vlan_ping.py, test/case/ietf_routing/ospf_basic.py, test/case/ietf_routing/ospf_multiarea.py, test/case/ietf_routing/ospf_unnumbered_interface.py, test/case/ietf_routing/static_routing.py, test/case/infix_interfaces/bridge_basic.py, test/case/infix_interfaces/bridge_fwd_dual_dut.py, test/case/infix_interfaces/bridge_fwd_sgl_dut.py, test/case/infix_interfaces/bridge_veth.py, test/case/infix_interfaces/bridge_vlan.py, test/case/infix_interfaces/bridge_vlan_separation.py, test/case/infix_interfaces/dual_bridge.py, test/case/infix_interfaces/ipv4_autoconf.py, test/case/infix_services/services_basic.py
Add the ability to configure interface speed, duplex and autoneg. Initially this was pared with YANG model deviations that restricted explicit interface speed and duplex when autoneg was enabled. But due to conflicting default states in YANG and the fact that statd also uses the same YANG meant this code was dropped.
Turning autoneg on (which is the default) is as simple as:
` > set interface x10 ethernet auto-negotiation enable true` 
However, when turning it off the kernel requires an explicit speed and duplex to be set. Ideally we would like to ensure this in the YANG model frontend, as mentioned above. This PR implements a check in the backend witch gives this error when turning off autoneg without an explicit speed and/or duplex (duplex has default):
```
> set interface x10 ethernet …
```
=> confd: add the ability to set speed, duplex and autoneg

src/confd/src/ietf-interfaces.c
The bridge should always be created with default pvid disabled.  This is both a security feature and fix to issue #310.
=> confd: always create bridge with default_pvid 0

.github/workflows/regression.yml, src/confd/bin/bootstrap, src/confd/yang/infix-ethernet-interface@2024-02-27.yang, src/statd/cli-pretty, src/statd/yanger, test/case/cli/cli-output/show-interface-e0.txt, test/case/cli/cli-output/show-interface-e1.txt
This PR adds out-good-octets and in-good-octets as augment in the infix-ethernet-interface yang model. These counters represents OctetsTransmittedOK and OctetsReceivedOK from ethtool.
Example CLI output:
```
root@infix-06-10-00:/> show interfaces name x10
...
eth-out-good-octets          : 4414
eth-in-good-octets           : 1897
....
```
=> statd: add good-octets counters

test/case/ietf_hardware/usb.py, test/case/misc/start_from_startup.py, test/infamy/util.py
Add new reboot test to test that units can start from startup config
- Refactor code from test/case/ietf_hardware/usb.py to test/infamy/util, to a function called wait boot
- Added test to be able to verify the existence of #311
- [x ] Refactoring (please detail in commit messages)
- [x ] Other (please describe):
Added test
=> Add reboot test

.github/workflows/build.yml, .github/workflows/regression.yml, test/env
Currently the regression tests runs twice when branches and PR:s originate from the same repo.  This commit adopts a fix suggested at
https://wildwolf.name/github-actions-how-to-avoid-running-the-same-workflow-multiple-times/
=> Run regression tests only once, either push or pull-request

test/case/infix_interfaces/ipv4_autoconf.py, test/infamy/iface.py
There was a race condition in the test ipv4_autoconf, that appeared on slow hardware (GitHub cloud runner,  a pc with kvm disabled), that locked-up the test forever.
- also fix a little bug in infamy/iface.py
=> Fix race condition in test

src/confd/src/ietf-interfaces.c
Fix VLAN inferring when using interface name IFNAME.VID to naming the interface.
Then set all VLAN settings properly as well
This fixes #329
=> Fix VLAN inference of traditional ifname.vid syntax

doc/ChangeLog.md, package/klish-plugin-sysrepo/klish-plugin-sysrepo.hash, package/klish-plugin-sysrepo/klish-plugin-sysrepo.mk, src/confd/bin/bootstrap, src/confd/src/ietf-routing.c, src/confd/yang/infix-routing@2024-01-09.yang, src/confd/yang/infix-routing@2024-03-06.yang
Fix issue #331, inconsistent naming 'enable' the terminology we use is 'enabled'
=> Fix redistribute default naming

package/querierd/querierd.mk, package/querierd/template.svc, patches/iproute2/0003-iplink_bridge-add-mcast_flood_always-bridge-option.patch, patches/iproute2/0004-bridge-mdb-Add-replace-support.patch, patches/linux/0018-net-bridge-avoid-classifying-unknown-multicast-as-mr.patch, patches/linux/0019-net-bridge-Ignore-router-ports-when-forwarding-L2-mu.patch, src/confd/src/ietf-interfaces.c, src/confd/yang/infix-if-bridge@2024-02-19.yang, test/.env, test/case/infix_interfaces/all.yaml, test/case/infix_interfaces/igmp_basic.py, test/case/infix_interfaces/igmp_vlan.py, test/docker/Dockerfile, test/env, test/infamy/multicast.py, test/infamy/topologies/1x4.dot, test/virt/quad/topology.dot.in
Initial IGMP/MLD filtering support for the Linux bridge model.  This PR brings per-bridge and per-VLAN settings to control basic multicast snooping[^1] settings:
- Enable multicast snooping on the bridge, or per VLAN
- Adjust querier mode (off, auto, proxy/NULL-only)
- Adjust query interval (1-1024 sec)
We have verified that the built-in querier function of the kernel works, in particular in a non-VLAN filtering setup.  However, since it only supports proxy/NULL queries in a per-VLAN setup we've decided against using it at all.  So all querier functionality is handled by a userspace daemon instead.
The upstream kernel support for multicast filtering is still a bit limited.  For example:
1. the only way to enable filtering of layer-2 (MAC) multicast, is to enable multicast snooping
2. …
=> Initial multicast filtering support for bridge

src/confd/bin/gen-interfaces
This PR fixes a regression in generating factory-config for systems that want a bridge by default for all types of interfaces.
=> Allow bridge in factory-config for all interface types

doc/ChangeLog.md, src/confd/src/ietf-interfaces.c, src/confd/yang/infix-if-bridge@2024-03-06.yang
This PR primarily addresses #328, and while inspecting the model the team decided to also take the time to improve the validation of port memberships in VLAN filtering bridges.
=> Bridge model fixes and improved restrictions

board/aarch64/dts/styx/styx.dtsi
Only port 2 has an SGMII compatible SERDES. When referencing the SERDES (comphy), the second argument must contain the port number in order for the comphy driver to pick the correct configuration.
=> board/aarch: styx: Fix SERDES connection to management CPU

patches/linux/0001-net-phy-add-support-for-PHY-LEDs-polarity-modes.patch, patches/linux/0002-net-mvmdio-Support-setting-the-MDC-frequency-on-XSMI.patch, patches/linux/0003-net-dsa-mv88e6xxx-Create-API-to-read-a-single-stat-c.patch, patches/linux/0004-net-dsa-mv88e6xxx-Give-each-hw-stat-an-ID.patch, patches/linux/0005-net-dsa-mv88e6xxx-Add-eth-mac-counter-group-support.patch, patches/linux/0006-net-dsa-mv88e6xxx-Limit-histogram-counters-to-ingres.patch, patches/linux/0007-net-dsa-mv88e6xxx-Add-rmon-counter-group-support.patch, patches/linux/0009-net-dsa-mv88e6xxx-Add-LED-infrastructure.patch, patches/linux/0010-net-dsa-mv88e6xxx-Add-LED-support-for-6393X.patch, patches/linux/0011-net-dsa-mv88e6xxx-Fix-timeout-on-waiting-for-PPU-on-.patch, patches/linux/0012-net-dsa-Support-MDB-memberships-whose-L2-addresses-o.patch, patches/linux/0013-net-phy-marvell10g-Support-firmware-loading-on-88X33.patch, patches/linux/0014-net-phy-marvell10g-Fix-power-up-when-strapped-to-sta.patch, patches/linux/0015-net-phy-marvell10g-Add-LED-support-for-88X3310.patch, patches/linux/0016-net-phy-marvell10g-Support-LEDs-tied-to-a-single-med.patch, patches/linux/0017-nvmem-layouts-onie-tlv-Let-device-probe-even-when-TL.patch, patches/linux/0018-net-bridge-avoid-classifying-unknown-multicast-as-mr.patch, patches/linux/0019-net-bridge-Ignore-router-ports-when-forwarding-L2-mu.patch, patches/linux/0020-net-dsa-Support-EtherType-based-priority-overrides.patch, patches/linux/0021-net-dsa-mv88e6xxx-Support-EtherType-based-priority-o.patch, patches/linux/0022-net-phy-Do-not-resume-PHY-when-attaching.patch, patches/linux/0023-net-dsa-mv88e6xxx-Improve-indirect-register-access-p.patch, utils/kernel-refresh.sh
With the Amethyst family, the indirect addressing mode used in multi-chip setups was improved by making common global functions (e.g. external MDIO bus, ATU, VTU) directly accessible through previously reserved registers.
Add support for this in `mv88e6xxx`.
Non-scientific measurements show that loading of startup-configs with north of 10 VLANs is roughly twice as fast with this feature in place.
Also, disable the kernel's default behavior of starting up a PHY as soon as a netdev driver attaches to it, avoiding the issue of signaling a physical link up to the link partner while the backing MAC is still disabled.
=> 6393 Multi-chip Register Access Improvements

patches/linux/0001-net-phy-add-support-for-PHY-LEDs-polarity-modes.patch, patches/linux/0002-net-mvmdio-Support-setting-the-MDC-frequency-on-XSMI.patch, patches/linux/0003-net-dsa-mv88e6xxx-Create-API-to-read-a-single-stat-c.patch, patches/linux/0004-net-dsa-mv88e6xxx-Give-each-hw-stat-an-ID.patch, patches/linux/0005-net-dsa-mv88e6xxx-Add-eth-mac-counter-group-support.patch, patches/linux/0006-net-dsa-mv88e6xxx-Limit-histogram-counters-to-ingres.patch, patches/linux/0007-net-dsa-mv88e6xxx-Add-rmon-counter-group-support.patch, patches/linux/0009-net-dsa-mv88e6xxx-Add-LED-infrastructure.patch, patches/linux/0010-net-dsa-mv88e6xxx-Add-LED-support-for-6393X.patch, patches/linux/0011-net-dsa-mv88e6xxx-Fix-timeout-on-waiting-for-PPU-on-.patch, patches/linux/0012-net-dsa-Support-MDB-memberships-whose-L2-addresses-o.patch, patches/linux/0013-net-phy-marvell10g-Support-firmware-loading-on-88X33.patch, patches/linux/0014-net-phy-marvell10g-Fix-power-up-when-strapped-to-sta.patch, patches/linux/0015-net-phy-marvell10g-Add-LED-support-for-88X3310.patch, patches/linux/0016-net-phy-marvell10g-Support-LEDs-tied-to-a-single-med.patch, patches/linux/0017-nvmem-layouts-onie-tlv-Let-device-probe-even-when-TL.patch, patches/linux/0018-net-bridge-avoid-classifying-unknown-multicast-as-mr.patch, patches/linux/0019-net-bridge-Ignore-router-ports-when-forwarding-L2-mu.patch, patches/linux/0020-net-dsa-Support-EtherType-based-priority-overrides.patch, patches/linux/0021-net-dsa-mv88e6xxx-Support-EtherType-based-priority-o.patch, patches/linux/0022-net-phy-Do-not-resume-PHY-when-attaching.patch, patches/linux/0023-net-dsa-mv88e6xxx-Improve-indirect-register-access-p.patch, patches/linux/0024-net-bridge-drop-delay-for-applying-strict-multicast-.patch
This kernel patch drops the initial delay to switch from flooding to strict filtering.
The main reason for this patch is RFC conformance and customer expectations.  At power on we assume the querier role by default and are expected to stop unknown flooding as soon as we have a membership report in place, not after 10 seconds.
A proper fix for upstreaming could be to add a knob to disable the delay.
- #334
=> kernel: import drop initial multicast filtering delay

src/statd/yanger
When the day of month is 1-9 the format did not match the yang model
This fixes #377 
=> yanger: Allow manufactering date to be day 1-9

utils/ixll, utils/libll.sh
Create a utility script where we can keep all of our favorite ways to ~~exploit~~leverage the fact that Infix devices all respond to ff02::1 by default.
=> utils: ixll: Add link-local wrappers for ping/ssh/scp

board/aarch64/dts/alder/alder.dtsi, patches/linux/0001-net-phy-add-support-for-PHY-LEDs-polarity-modes.patch, patches/linux/0002-net-mvmdio-Support-setting-the-MDC-frequency-on-XSMI.patch, patches/linux/0003-net-dsa-mv88e6xxx-Create-API-to-read-a-single-stat-c.patch, patches/linux/0004-net-dsa-mv88e6xxx-Give-each-hw-stat-an-ID.patch, patches/linux/0005-net-dsa-mv88e6xxx-Add-eth-mac-counter-group-support.patch, patches/linux/0006-net-dsa-mv88e6xxx-Limit-histogram-counters-to-ingres.patch, patches/linux/0007-net-dsa-mv88e6xxx-Add-rmon-counter-group-support.patch, patches/linux/0009-net-dsa-mv88e6xxx-Add-LED-infrastructure.patch, patches/linux/0010-net-dsa-mv88e6xxx-Add-LED-support-for-6393X.patch, patches/linux/0011-net-dsa-mv88e6xxx-Fix-timeout-on-waiting-for-PPU-on-.patch, patches/linux/0012-net-dsa-Support-MDB-memberships-whose-L2-addresses-o.patch, patches/linux/0013-net-phy-marvell10g-Support-firmware-loading-on-88X33.patch, patches/linux/0014-net-phy-marvell10g-Fix-power-up-when-strapped-to-sta.patch, patches/linux/0015-net-phy-marvell10g-Add-LED-support-for-88X3310.patch, patches/linux/0016-net-phy-marvell10g-Support-LEDs-tied-to-a-single-med.patch, patches/linux/0017-nvmem-layouts-onie-tlv-Let-device-probe-even-when-TL.patch, patches/linux/0018-net-bridge-avoid-classifying-unknown-multicast-as-mr.patch, patches/linux/0019-net-bridge-Ignore-router-ports-when-forwarding-L2-mu.patch, patches/linux/0020-net-dsa-Support-EtherType-based-priority-overrides.patch, patches/linux/0021-net-dsa-mv88e6xxx-Support-EtherType-based-priority-o.patch, patches/linux/0022-net-phy-Do-not-resume-PHY-when-attaching.patch, patches/linux/0023-net-dsa-mv88e6xxx-Improve-indirect-register-access-p.patch, patches/linux/0024-net-bridge-drop-delay-for-applying-strict-multicast-.patch, patches/linux/0025-net-dsa-mv88e6xxx-Honor-ports-being-managed-via-in-b.patch
Even when `managed = "in-band-status";` was specified on a port,
mv88e6xxx would insist on forcing the values that were supposed to be
automatically picked up by the MAC via in-band signaling.
In the case of USXGMII links on 6393X, forcing the link bit would
sometimes, for reasons that are not understood, cause the SERDES to
reset its USXGMII link partner base page (register 4.0xf0a2) to 0,
which it would then interpret as 10M/half-duplex. As a result, the
SERDES would erroneously perform rate-matching to 10M on egress
towards the PHY (which is configured for 10G/full-duplex), leading to
nothing but dropped packets and much sadness.
This can most easily be reproduced by the following setup:
```
.------------.
|        .-----.   .-------.
|        | p9  +---+ 3310P +--.
| 6393X  :-----: …
```
=> Fix USXGMII Auto-negotiation Issue

board/common/qemu/Config.in.in, board/common/qemu/qemu.sh, board/x86_64/board.mk, board/x86_64/grub.cfg, test/env, test/virt/quad/topology.dot.in
*  Stop testing on raw images, create qcow2 instead
*  Use same console for Qemu and make test-sh (hvc0)
*  Change so the tests by default now use BIOS boot, 
this can be changed by change in the topology 
to use infix-kernel-x86_64 template instead of infix-bios-x86_64
=> Run tests using bootloader (grub)

patches/linux/0001-net-phy-add-support-for-PHY-LEDs-polarity-modes.patch, patches/linux/0002-net-mvmdio-Support-setting-the-MDC-frequency-on-XSMI.patch, patches/linux/0003-net-dsa-mv88e6xxx-Create-API-to-read-a-single-stat-c.patch, patches/linux/0004-net-dsa-mv88e6xxx-Give-each-hw-stat-an-ID.patch, patches/linux/0005-net-dsa-mv88e6xxx-Add-eth-mac-counter-group-support.patch, patches/linux/0006-net-dsa-mv88e6xxx-Limit-histogram-counters-to-ingres.patch, patches/linux/0007-net-dsa-mv88e6xxx-Add-rmon-counter-group-support.patch, patches/linux/0009-net-dsa-mv88e6xxx-Add-LED-infrastructure.patch, patches/linux/0010-net-dsa-mv88e6xxx-Add-LED-support-for-6393X.patch, patches/linux/0011-net-dsa-mv88e6xxx-Fix-timeout-on-waiting-for-PPU-on-.patch, patches/linux/0012-net-dsa-Support-MDB-memberships-whose-L2-addresses-o.patch, patches/linux/0013-net-phy-marvell10g-Support-firmware-loading-on-88X33.patch, patches/linux/0014-net-phy-marvell10g-Fix-power-up-when-strapped-to-sta.patch, patches/linux/0015-net-phy-marvell10g-Add-LED-support-for-88X3310.patch, patches/linux/0016-net-phy-marvell10g-Support-LEDs-tied-to-a-single-med.patch, patches/linux/0017-nvmem-layouts-onie-tlv-Let-device-probe-even-when-TL.patch, patches/linux/0018-net-bridge-avoid-classifying-unknown-multicast-as-mr.patch, patches/linux/0019-net-bridge-Ignore-router-ports-when-forwarding-L2-mu.patch, patches/linux/0020-net-dsa-Support-EtherType-based-priority-overrides.patch, patches/linux/0021-net-dsa-mv88e6xxx-Support-EtherType-based-priority-o.patch, patches/linux/0022-net-phy-Do-not-resume-PHY-when-attaching.patch, patches/linux/0023-net-dsa-mv88e6xxx-Improve-indirect-register-access-p.patch, patches/linux/0024-net-bridge-drop-delay-for-applying-strict-multicast-.patch, patches/linux/0025-net-dsa-mv88e6xxx-Honor-ports-being-managed-via-in-b.patch, patches/linux/0026-net-dsa-mv88e6xxx-Fix-port-policy-config-on-6393X.patch, patches/linux/0027-net-dsa-mv88e6xxx-Limit-rsvd2cpu-policy-to-user-port.patch
For packets with a DA in the IEEE reserved L2 group range, originating from a CPU, forward it as normal, rather than classifying it as management.
```
bridge (group_fwd_mask 0x4000)
/ |  \
swp1 swp2 tap0
\   /
(mv88e6xxx)
```
We've created a bridge with a non-zero `group_fwd_mask` (allowing LLDP in this example) containing a set of ports managed by `mv88e6xxx` and some foreign interface (e.g. an L2 VPN tunnel).
Since an LLDP packet coming in to the bridge from the other side of `tap0` is eligable for tx forward offloading, a FORWARD frame destined for `swp1` and `swp2` would be send to the conduit interface.
Before this change, due to `rsvd2cpu` being enabled on the CPU port, the switch would try to trap it back to the CPU. Given that the CPU is trusted, instead assume that it indeed …
=> Support non-zero `group_fwd_mask` bridges with `mv88e6xxx` ports

board/common/rootfs/etc/lldpd.d/disabled-ports.conf, doc/ChangeLog.md, package/confd/confd.conf, src/confd/bin/bootstrap, src/confd/src/dagger.c, src/confd/src/dagger.h, src/confd/src/ietf-interfaces.c, src/confd/src/infix-dhcp.c, src/confd/yang/infix-hardware@2024-04-25.yang
- Disable flow control by default on Ethernet ports, both with and without autoneg
- Disable lldpd on `dsa0` interface, added to `board/common` in case of future devices
=> Disable flow control

board/common/uboot/uboot.mk
Now that RAUC can have multiple keys in its keyring, make sure that the same keys are built in to any U-Boot image as well.
=> Multiple trusted keys in U-Boot

doc/scripting.md
Adding script examples, primarily for production tests
- reading out eeprom/vpd data (sysrepocfg)
- LED testing (shell/echo)
- power supply sensor testing (shell/cat)
- Ethernet port test - example for looping ports (CLI setup)
A reference to a production test script for the first three items would be great extension to this.
The 4th item (Ethernet port configuration for looping) should perhaps be documented elsewhere.
Maybe in Networking Lego page?
=> Adding scripting examples relevant for production testing  

doc/ChangeLog.md, doc/container.md, src/confd/bin/gen-interfaces, src/confd/src/ietf-interfaces.c
- Create factory bridges with IGMP/MLD snooping enabled by default
- Create VETH interfaces with their custom MAC address
- Update documentation for container around VETH pairs
=> Factory bridge multicast and fix for veth custom mac address

board/common/rootfs/etc/iproute2/rt_addrprotos, doc/developers-guide.md, doc/override-package.md, patches/iproute2/6.7.0/0001-iplink_bridge-add-mcast_flood_always-bridge-option.patch, patches/iproute2/6.7.0/0002-ipaddress-accept-symbolic-names-also-for-show.patch
While working on a customer feature I realized it was not possible to do `ip addr show profinet`.  Turns out that even though a lot has happened with iproute2 v6.7.0, this tiny little thing is still not supported.
Also, while reviewing documentation I cleaned up some grammar and simplified parts of the Devloper's Guide.
=> Add support for `ip addr show proto name` & devguide update

doc/ChangeLog.md, src/confd/bin/gen-interfaces, src/confd/src/ietf-interfaces.c, test/case/ietf_interfaces/all.yaml, test/case/ietf_interfaces/ipv6_address.py
Fix ordering of dagger script execution for dynamic interfaces such as bridges, VETH pairs, etc.
Also included, a minor change for end-customers with bridges in their `factory-config`.
=> Fix #473: bridges never get IPv6 autoconf enabled

patches/netopeer2/2.2.28/0001-Allow-factory-as-copy-from-only-in-rpc-copy-config.patch, patches/netopeer2/2.2.28/0002-disable-local-users.patch, patches/netopeer2/2.2.28/0003-UPSTREAM-maain-BUGFIX-clear-url-protocolos.patch, patches/netopeer2/2.2.28/0004-UPSTREAM-main-UPDATE-zero-the-whole-np2srv-struct.patch, patches/netopeer2/2.2.28/0005-UPSTREAM-main-BUGFIX-wrong-param-order.patch, patches/sysrepo/2.10.1/0001-sysrepo-plugind-add-support-for-running-in-foregroun.patch, patches/sysrepo/2.10.1/0002-Allow-SR_EV_DONE-to-return-any-error-to-sysrepocfg.patch, patches/sysrepo/2.10.1/0003-Allow-to-copy-from-factory-default.patch, patches/sysrepo/2.10.1/0004-Add-z-switch-to-sysrepoctl-to-install-factory-config.patch, patches/sysrepo/2.10.1/0005-modinfo-BUGFIX-memory-leak.patch, patches/sysrepo/2.10.1/0006-sub-ntf-BUGFIX-proper-invalid-FD-check.patch, src/confd/yang/confd.inc
For netopeer2 we need to patch away local-users, since if it is enabled netopeer2 requires all users that should be allowed to use netconf to also be configured in ietf-netconf-server.
Also add some upstream patches.
=> Bump libyang, libnetconf2, sysrepo and netopeer2

board/common/uboot/scripts/ixpreboot.sh
For systems with multiple paths to the network, different situations may call for different paths to be used. Therefore, allow the user to override the active interface via the environment on the auxiliary partition.
The default (defined the bootloader's device tree) is still used in cases when nothing else is specified in the environment.
=> uboot: Support overriding the interface used for netbooting Infix

board/aarch64/dts/styx/styx.dtsi
In order for the probe logic to source product data from a VPD, it must be marked as such. Otherwise we end up in a scenario where the data is collected, but not hoisted up to the system level, leaving the system without a defined base-MAC for instance.
=> board/aarch64: styx: Source product data from VPD

doc/testing.md, src/statd/python/yanger/yanger.py, test/env, test/infamy/container.py, test/infamy/util.py, test/test.mk
This PR increases the robustness of the Infix `yanger` helper.  Basically, instead of bailing out with `sys.exit(1)`, causing `statd` to fail and automatically cause a non-working operational datastore, we allow external commands to fail and then return empty objects/arrays to the respective data parsers.
For example, asking the operational datastore for the status of a container before the container has been started properly should not b0rk the datastore, but rather return `None` information.  Same as if listing all containers.
The test framework has also been made slightly more fault tolerant by adding a retry of container commands.
Fixes #558 and #568
=> Increase robustness of operational datastore

package/confd/tmpfiles.conf, src/confd/bin/.confdrc, src/confd/bin/bootstrap, src/confd/bin/load, src/confd/confdrc, src/confd/configure.ac, src/confd/share/Makefile.am, src/confd/share/README, src/confd/share/test.d/10-infix-services.json, src/confd/share/test.d/10-nacm.json, src/confd/share/test.d/10-netconf-server.json, src/confd/share/test.d/10-system.json, src/confd/share/test.d/Makefile.am
Currently, it's not possible to run infix tests from an external project (based on infix) due to an incompatibility between the
configuration used in the tests (the default configuration within the image generated by the external project) and the infix
base configuration expected by the test cases. 
Therefore, a simple configuration specifically for testing purposes needs to be generated within an image. 
This test-config should only be generated and loaded when the device is in test mode.
=> Generate and load test-config when in test-mode

board/common/Config.in, board/common/mkdisk.sh, board/common/post-image.sh, doc/test-arch.md, doc/testing.md, src/confd/share/factory.d/Makefile.am, src/confd/share/failure.d/Makefile.am, src/confd/share/test.d/Makefile.am
To support testing, the 'test-config.cfg' has been introduced in Infix. Additionally, a test mode for the running image is required for this configuration to be applied.
Basically the 'test-config' will only be generated and loaded when the device is in 'test-mode', which is determined by the presence of the '/mnt/aux/test-mode file'. However, placing this file via the Qeneth system proved to be inconvenient in the test environment. Therefore, the entire image is built in test mode, with the 'test-mode' file preloaded onto the disk image (specifically in the auxiliary partition).
To support this, a new variable, '(bool) DISK_IMAGE_TEST_MODE', has been introduced:
* 'enabled': the image will be built in the test mode;
* 'disabled': the image will be built in the standard mode.
=> Introduce Test Mode for Build

Makefile, test/env, test/test.mk
Minor adjustments have been made to enable calling infix tests from an external make test target. This essentially allows running any external test (or a group of tests) using the 9pm tool.
=> Enable Running Infix Tests from External Project

src/confd/src/ietf-syslog.c, src/confd/src/ietf-system.c
Fixes minor Coverity weekly scan issues as well as some linter warnings from clang-tidy.
=> Minor Coverity Scan fixes

doc/developers-guide.md, utils/gh-dl-artifact.sh
This will make it easier to locally test images when reviewing PRs, and will also be a useful tool when running tests on physical test rigs.
[skip ci]
=> utils/gh-dl-artifact.sh: Add support script to download artifacts

doc/ChangeLog.md, src/confd/src/core.c, src/confd/src/core.h, src/confd/src/ietf-interfaces.c, test/case/infix_interfaces/igmp_basic/test.py
This PR fixes the EUI-64 based IPv6 autoconf address on bridges and updates the IGMP basic test.                                                                                                                                            
The EUI-64 address is fixed by explicitly assigning the base mac address to the bridge when creating it. Strangely, this messes with some timing in the bridge, causing the first multicast querier message sent to the bridge from user-space to be lost. This is caused by the bridge using the "NOOP" scheduler (noop_enqueue()) for a short period of time while the interface is starting up. To avoid the test-case failing when this happens we introduce a retry that will wait for the second query message. This is a bit strange in the case of a software device such …
=> Fix eui 64 based ipv6 addresses

board/common/rootfs/usr/sbin/container, doc/ChangeLog.md, doc/container.md, src/confd/src/infix-containers.c, src/execd/execd.c, src/klish-plugin-infix/xml/containers.xml, src/klish-plugin-infix/xml/infix.xml, src/statd/python/yanger/yanger.py
Misc. fixes to annoying regressions and missing functionality.
=> Misc bugfixes

package/Config.in
Almost cosmetic bugfix adding a missing " in date-cpp package reference, which caused a build time warning
=> bug: Add missing " in date-cpp package reference

board/common/Config.in, board/common/mkdisk.sh, board/common/post-image.sh, doc/ChangeLog.md, test/.env, test/docker/Dockerfile, test/env, test/inject-test-mode, test/virt/dual/topology.dot.in, test/virt/quad/topology.dot.in
The test mode, introduced at the config/build phase (commit 241f3f2), causes the device to start in test-mode when used in GNS3 (or other environments). This has unintentionally become the default configuration for the image, which is not desirable and is only acceptable for the Infix test system. 
With this update, the original configuration is preserved, and the test mode is applied only within the test environment.
=> Introduce Test Mode only within Test Environment

src/statd/python/yanger/yanger.py, src/statd/statd.c
This PR removes the statd interface netlink code and improve speed of operational interface data.
This is a major redesign of statd interface handling. The goal here is to reduce the time it takes for statd to produce operational data for all interfaces on larger iron. Which manifested itself most notably in the CLI command "show interfaces".
This PR removes the netlink interface subscriptions done by the statd c code. Instead statd now subscribes to the ietf-interfaces base path which means it will be invoked for all interfaces. If the user (sysrepo) has specified an explicit interface name such as eth0, it will be extracted by statd and passed down to Yanger.
This PR also modifies Yanger to fit this new modus. No explicitly passed interface name now means all interfaces.
The main …
=> Statd: improve speed of interface data 

test/case/infix_services/infix_services.yaml
As detailed in the comment, we disable this test pending a fix for #654 which will allow us to detect when the host won't be able to sniff LLDP frames.
=> test: Disable services_basic

doc/ChangeLog.md, src/confd/share/migrate/1.0/10-infix-shell-type.sh, src/confd/share/migrate/1.1/10-infix-routing-type.sh, src/confd/src/ietf-interfaces.c, src/klish-plugin-infix/xml/infix.xml, test/infamy/restconf.py
- Fixes a regression introduced on `main` while fixing issue #658
- Check for `control-plane-protocol` in `startup-config` before migrating and causing empty `startup-config`
- Return `None` on 404 return for fetching a given operational XPath in RESTCONF test backend
- Fix `tcpdump` permissions for `admin` user in CLI
=> Fix test issues after adding veth-delete test

utils/gh-dl-artifact.sh
The `gh-dl-artifact` script is now able to find artifacts in any run associated with a particular commit, and if the one it finds is the result of a release build, that is now correctly extracted.
=> Support downloading artifacts from release builds

doc/branding.md, doc/introduction.md
Infix now supports static `/etc/factory-config.cfg` from a rootfs overlay or `/usr/share/product/<VPD.PRODUCT>/etc/factory-config.cfg` in addition to the autogenerated `/run/confd/*-config.gen` files.
Update the Branding & Releases document with a bit more information on this rather complex topic.
=> doc: expand on static vs dynamic factory-config

board/common/uboot/scripts/ixboot.sh, board/common/uboot/scripts/ixprepdhcp.sh
- Skip `bootmenu` when developer mode is enabled, drop straight into the shell
- Skip DHCP if the network has already been statically configured by the user
- Ensure that the path for HTTP GETs include a leading slash
Example of netbooting over HTTP without a DHCP server:
```
[...]
Valid boot device found on mmc1 (order: net)
Press Ctrl-C NOW to override the default boot sequence
Run "bootmenu" to interactively select a boot device
(cn9130-crb) setenv ipaddr 198.18.106.2 
(cn9130-crb) setenv netmask 255.255.255.0
(cn9130-crb) setenv serverip 198.18.106.1
(cn9130-crb) setenv bootfile http://198.18.106.1/rootfs.itb
(cn9130-crb) run boot_net
net: Preparing...
proto=http
bootfile=198.18.106.1:/rootfs.itb
mvpp2 mvpp2-0: incorrect phy mode
mvpp2-1 Waiting for PHY auto negotiation to …
```
=> Uboot improvements

src/statd/python/cli_pretty/cli_pretty.py, src/statd/python/yanger/yanger.py, test/case/cli/run.sh
Fix flaky ietf-routing unit tests.
Prior to this patch, there was a unit-test race between Yanger (sysrepo emulator) and cli-pretty, where the local system time could change between crafting the data and printing it. This caused the CLI output to change and the ietf-routing unit test to fail.
Fixes #668
=> test: use static time in ietf-routing unit tests

src/klish-plugin-infix/src/infix.c
Don't show "internal" interfaces in "show interface name" tab completion.
I initially implemented this in the `show` command, as "show ifnames". It worked but was unreasonably slow for some reason, perhaps due to the `show` init code that does resize and such. As there's no variables involved I abandoned that approach and inlined it instead.
=> cli: hide internal interfaces in tabcomplete

src/confd/src/ietf-system.c, test/case/ietf_interfaces/Readme.adoc, test/case/ietf_interfaces/iface_phys_address/Readme.adoc, test/case/ietf_interfaces/iface_phys_address/test.py, test/case/ietf_interfaces/ipv4_address/Readme.adoc, test/case/ietf_interfaces/ipv4_address/test.py, test/case/ietf_interfaces/ipv4_autoconf/Readme.adoc, test/case/ietf_interfaces/ipv4_autoconf/test.py, test/case/ietf_routing/ospf_multiarea/Readme.adoc, test/case/ietf_routing/ospf_multiarea/test.py, test/case/ietf_system/add_delete_user/Readme.adoc, test/case/ietf_system/add_delete_user/test.py, test/case/ietf_system/hostname/Readme.adoc, test/case/ietf_system/hostname/test.py, test/case/ietf_system/timezone/Readme.adoc, test/case/ietf_system/timezone/test.py, test/case/ietf_system/timezone_utc_offset/Readme.adoc, test/case/ietf_system/timezone_utc_offset/test.py, test/case/ietf_system/upgrade/Readme.adoc, test/case/ietf_system/upgrade/test.py, test/case/ietf_system/user_admin/Readme.adoc, test/case/ietf_system/user_admin/test.py
Fix typos and improve some test coverage
=> Update some tests

src/confd/src/infix-containers.c
Fix a double free in the memory minefield surrounding container hostname provisioning. The hostnamefmt() function already does free() on success.
This caused all sorts of mayhem when working with multiple containers. However it mainly manifested itself by some containers not starting due to there activation script being polluted with gibberish name data. Your symptom might be different..
``container --hostname foobar --net veth0k -r always \
create ^S@`M-}^G docker://ghcr.io/kernelkit/curios:edge``
I haven't looked into it but is it really legit to free memory returned from the various lydx_ functions used here?
It seems to work as intended but it looks risky at a glance.
=> confd: fix double free of container hostname

doc/ChangeLog.md, doc/qos.md
For packets containing both a VLAN tag and an IP header, PCP priority takes precedence over DSCP priority (**not** vice versa).
This is how QoS is currently handled and how we want it to be by default. 
No code change, just doc change.
=> Doc fix on QoS. PCP takes priority over DSCP for tagged IP packets

doc/ChangeLog.md
Updating existing formulations for changes and fixes for OSPF.
In particular, the limitation introduced for areas per interface (not interfaces per area)
=> Doc fixes in ChangeLog v24.10.0 related to OSPF

src/statd/python/yanger/yanger.py
The interface operational data was missing the 'admin-status' parameter, which indicates whether an interface is administratively enabled or disabled. 
To resolve this, the 'admin-status' was added to the 'yanger' library, allowing 'statd' to retrieve and include this parameter in the operational data.
=> Statd: Add 'admin-status' to Interface Operational Data

board/common/uboot/scripts/ixprepdhcp.sh
Fix repeated HTTP netboot attempts. Avoid having to supply `serverip` when `proto://path` format is used for `bootfile`.
=> U-Boot HTTP Netboot Fixes

board/aarch64/rootfs/usr/share/product/dcp-sc-28p/etc/finit.d/available/iitod.conf, doc/ChangeLog.md, package/finit/0001-Only-mark-rdeps-dirty-if-main-service-is-nohup.patch
This PR disables software control of port LEDs, for details, see #670 
Also in this PR, a backport of a Finit patch to reduce the impact of reloading (SIGHUP) services like `syslogd`, which many other services in Infix depend of (as a barrier).  The patch makes sure a HUP-capable service (A) do not trigger reload/restart of other services that depend on A.
=> Disable software LED control of port LEDs

.github/CHECKLIST.md, .github/pull_request_template.md
After the v24.10.0 snafu (see #736) I thought it was a good idea to start a discussion about having a checklist (reminders) for maintainers:
- Checklist for Code Review (PRs)
- Checklist for Releases
<https://github.com/kernelkit/infix/blob/checklist/.github/CHECKLIST.md>
=> Checklist for code review and releases

board/common/rootfs/usr/libexec/infix/init.d/20-nameif
Sometimes the interface creation are done, but
the sysfs is not, this gap we sometimes finds
in the nameif script. Wait out the sysfs creation
if running a DSA switch.
Fix #685
=> Make detection of DSA interface more robust

Config.in, board/common/post-build.sh
Some customers would like to seamlessly upgrade between their branded Infix-based software and vanilla Infix.  E.g., for testing of new features and end-customer support.
This PR adds support for overriding the default compatible string, which by default is taken from `INFIX_IMAGE_ID`, created from the `INFIX_ID` in the defconfig and `BR2_ARCH`.  This new setting, `INFIX_COMPATIBLE` is by default `INFIX_IMAGE_ID`.
Background, the `INFIX_IMAGE_ID` is also used for the image file names, as well as the tarballs, so overriding that in the defconfig has wider implications.  Hence this extension.
=> Add support for overriding the compatible string

board/aarch64/r2s/rootfs/etc/factory-config.cfg
- add default-deny-all rule from 2341e07
- enable iburst for the ntp client (quicker initial sync)
- bump meta version (to skip .cfg migration at boot)
=> Update r2s factory-config

board/common/post-image.sh
Follow-up to cedb654, see
- #755
=> Use INFIX_COMPATIBLE also for aux partition's rauc.status

test/env, test/test.mk
This will facilitate running infix tests from external projects:
- eliminate the need for an external topology.dot.in file
- eliminate the requirement to manually provide external image name
Fixes #763
=> Simplify Running Infix Tests from External Projects

test/case/ietf_interfaces/vlan_ping/Readme.adoc, test/case/ietf_interfaces/vlan_ping/test.py, test/case/ietf_routing/Readme.adoc, test/case/ietf_routing/ietf_routing.yaml, test/case/ietf_routing/ospf_bfd/Readme.adoc, test/case/ietf_routing/ospf_bfd/test.py, test/case/ietf_routing/ospf_bfd/topology.dot, test/case/ietf_routing/ospf_bfd/topology.svg, test/infamy/netns.py, test/infamy/tap.py
- Generalize the existing `IsolatedMacVlan` class to support creating namespaces with multiple ports
- Provide a Two-Port MAC Relay (TPMR) as an example implementation, which by default just relays frames between two ports, but can dynamically be set to block frames from passing through it. This is useful to test fail-over behavior of various protocols
- Add a test of BFD fail-over in combination with OSPF, using the new TPMR device
In order for the TPMR to act as a bridge, the mode of the MACVLANs has been changed to `passthru`, which allows it to receive all packets from its lower interface, and also lets it transmit unicast packets with any SA without triggering the kernel's spoof protection logic. This also enables us to use the parent interface's `promiscuity` value as an indicator …
=> test: Multi-Port Network Namespaces

test/case/ietf_interfaces/igmp_vlan/test.py, test/case/ietf_routing/ospf_bfd/test.py, test/case/ietf_routing/ospf_multiarea/test.py, test/infamy/netconf.py, test/infamy/restconf.py
This fix #804 and stabalize ospf_multiarea and ospf_bfd
=> Put config dicts

doc/ChangeLog.md, doc/networking.md
Add documentation of forwarding IEEE reserved group addresses to bridge section of networking documentation
=> Documentation of forwarding IEEE reserved group addresses

patches/rauc/1.11.3/0003-src-install-print-bootname-when-checking-slot.patch, patches/rauc/1.11.3/0004-src-main-add-warning-banner-at-start-of-installation.patch
Add two patches which improve upgrade output.
Prints the bootname during slot probing. This patch is sent upstream but not reviewed yet.
```
40% Updating slots
40% Checking slot rootfs.1 (secondary)
46% Checking slot rootfs.1 (secondary) done.
46% Copying image to rootfs.1
```
Print a "standard warning banner" at start of install.
```
rauc install tftp://192.168.122.1/infix-x86_64.pkg
+------------------------------------------------------------------------------+
|                                                                              |
|      [!] Installation might take a while. DO NOT power off the device.       |
|                                                                              |
|                   Please wait while the upgrade completes.                   |
| …
```
=> rauc: improve upgrade output

test/case/ietf_interfaces/bridge_vlan_separation/Readme.adoc, test/case/ietf_interfaces/bridge_vlan_separation/test.py, test/spec/Readme.adoc
- Verify that broadcast packets are also properly moved accross the bridge, i.e. the broadcast packets sent from vlan interface VLAN10 do not reach VLAN20
=> Verify that bridge vlan separation works properly for broadcast packets

test/case/ietf_routing/Readme.adoc, test/case/ietf_routing/ietf_routing.yaml, test/case/ietf_routing/ospf_basic/test.py, test/case/ietf_routing/ospf_default_route_advertise/Readme.adoc, test/case/ietf_routing/ospf_default_route_advertise/test.py, test/case/ietf_routing/ospf_default_route_advertise/topology.dot, test/case/ietf_routing/ospf_default_route_advertise/topology.svg
And add a test pass for redistribute static routes in ospf_basic
=> Add a new test for default-route-advertise

.github/workflows/build.yml, board/common/mkrauc.sh, board/common/post-build.sh, doc/ChangeLog.md, doc/branding.md, external.mk, infix.mk, test/infamy/netns.py, test/test.mk
This will make it easier to correlate an image to the corresponding PR and or commit.
=> .github: Set usable version strings on PR builds

src/confd/bin/dagger, src/confd/src/dagger.c, src/confd/src/ietf-interfaces.c
When reconfiguring the system many times (seen during regression testing), the RAM usage of keeping all generations around starts to add up.
A tmpfs file, no matter how small, will always consume at least one full page (4k). So one generation of tiny setup scripts and log files can end up locking :warning: 1 MB :warning:  of memory.
Therefore: Once we're done with a generation, archive it in a compressed tarball, which typically fits inside a single 4k page. Limit the total number of archives to 10. This should give full visibility into the history of a system in all normal situations, while still allowing hammering systems with reconfig cycles in testing scenarios.
=> Dagger memory usage

package/rousette/0001-restconf-report-the-list-key-values-when-they-differ.patch, package/rousette/0002-uri-rename-url-encoding-to-percent-encoding.patch, package/rousette/0003-uri-correct-x3-rule-class-names.patch, package/rousette/0004-restconf-parser-should-work-on-raw-percent-encoded-p.patch, package/rousette/0005-restconf-list-key-values-checking-must-respect-libya.patch, package/rousette/0006-tests-test-querying-lists-with-union-keys.patch, package/rousette/0007-error-handling-in-sysrepo-has-changed.patch, package/rousette/0008-restconf-support-fields-query-parameter.patch, package/rousette/0009-cmake-adhere-to-CMP0167.patch, package/rousette/0010-Fix-compatibility-with-pam_wrapper-1.1.6.patch, package/rousette/0011-tests-add-missing-pragma-once.patch, package/rousette/0012-tests-extend-clientRequest-wrappers-interface-and-us.patch, package/rousette/0013-tests-move-stuff-from-the-header-file-into-cpp-file.patch, package/rousette/0014-tests-rename-datastoreUtils-to-event_watchers.patch, package/rousette/0015-tests-rename-NotificationWatcher.patch, package/rousette/0016-tests-make-NotificationWatcher-reusable.patch, package/rousette/0017-tests-helper-function-to-construct-server-URI.patch, package/rousette/0018-tests-make-SSEClient-reusable.patch, package/rousette/0019-tests-fix-deadlock-in-tests.patch, package/rousette/0020-restconf-make-as_restconf_notification-reusable.patch, test/infamy/restconf.py
This fix the issue when query an instance which have an identy-ref as a key (ietf-routing:routing/control-plane-protocols/control-plane-protcol)
Adding nginx_lua_support to be able to keep compatibility with python requests. It transform the urls, and remove all %3A, replace them with :
This fix #781 
=> Add upstream patches for rousette

infix.mk
INFIX_OEM_PATH is `""` by default (i.e., not empty in `make`'s eyes). So we called `git` with `-C ""`, which it interpreted as "from the current directory" and thus we sourced the autogenerated build id from _buildroot_ instead of Infix.
Therefore, make sure to strip any quotes from the OEM path before determining the top directory.
=> build: Source build id from the correct repo, fix #872

utils/generate-defconfig.sh
Useful to only create a new image with only small diff with for example aarch64_defconfig.
example:
If the only diff is the VENDOR, instead of KernelKit you want 'foobar'. create a file with the change:
INFIX_VENDOR="foobar"
and call ./utils/generate-defconfig.sh -b aarch64_defconfig -c foobar-diff.conf -o configs/foobar_defconfig
=> Add script for merging defconfigs

src/statd/python/yanger/ietf_interfaces/container.py, test/case/infix_services/ssh_key_authentication/test.py, test/case/infix_services/ssh_server_config/test.py, test/infamy/netconf.py, test/infamy/netutil.py, test/infamy/ssh.py
Due to #902 (which has not been root caused at this time), podman may indicate the existance of an interface that yanger is not able to locate in any namespace. Therefore, make sure that we verify that the interface was actually found before trying to create the operational data for it.
=> yanger: Handle the case when a container interface can not be found

doc/ChangeLog.md, src/test-mode/src/test-mode.c
The context was aquired but never released, this caused a lockup in sysrepo.
This fix #861
=> Fix error when running 251+ reconfigurations (in test-mode)

.github/SUPPORT.md, board/aarch64/cn9130-crb/README.md, board/aarch64/r2s/README.md, doc/ChangeLog.md, doc/management.md, src/confd/yang/infix-services.yang
Adding rudimentary documentation (enabling/disabling, etc) on managing Infix 
- via console port
- Web, Web Console and RESTCONF
- and updating the existing documentation on SSH server
Note, information on how to configure management via NETCONF remains to be documented.
Minor change to YANG model help text for enabling/disabling for RESTCONF (infix-system.yang).
This model has already had its revision updated since previous Infix release.
=> Doc console and other management interfaces

doc/ChangeLog.md, src/confd/src/ietf-system.c
The problem was that the sysrepo callback was never called, except on update (not availible on startup)
This fix #777
=> Fix issue with storing authorized SSH key to startup

doc/ChangeLog.md
This is a bugfix release, mostly regarding bgp, but was also some intresting fixes in zebra:
<pre>
Add missing new line for help string
Add missing proto translations
Correctly report metrics
Fix crash during reconnect
Fix snmp walk of zebra rib
Let's use memset instead of walking bytes and setting to 0
Separate zebra ZAPI server open and accept
Unlock node only after operation in zebra_free_rnh()
</pre>
Full changelog: https://github.com/FRRouting/frr/releases/tag/frr-9.1.3
=> Bump FRR to 9.1.3

board/common/qemu/Config.in.in
Pointer authentication emulation is expensive.  By default, QEMU use the standard cryptographic algorithm (QARMA5), which is very time consuming.  This PR switches to the fast implementation.
=> Use fast pointer authentication emulation for aarch64

utils/generate-defconfig.sh
Example: one common.conf and one arch-specific config
=> generate-defconfig.sh: Allow to have multiple change configurations

src/confd/yang/infix-lldp.yang, src/statd/python/yanger/__main__.py, src/statd/python/yanger/infix_lldp.py, src/statd/statd.c, test/case/infix_services/Readme.adoc, test/case/infix_services/infix_services.yaml, test/case/infix_services/lldp_admin_status/Readme.adoc, test/case/infix_services/lldp_admin_status/lldp_admin_status.adoc, test/case/infix_services/lldp_admin_status/test.py, test/case/infix_services/lldp_admin_status/topology.dot, test/case/infix_services/lldp_admin_status/topology.svg, test/case/infix_services/lldp_enable_disable/test.py, test/infamy/lldp.py
This PR introduces verification for the admin-status configuration, ensuring proper handling of 
LLDP administrative states. Additionally, it includes the implementation of statd for retrieving LLDP 
remote-systems-data from the operational datastore.
=> Verify LLDP administrative states

src/confd/src/ietf-system.c
Future Infix defconfigs for smaller system may exclude Frr and set all routes directly in the kernel.  So failing to add a user to the `frrvty` group should not cause an error, hence the new `group_exists()` function.
Note, the new `*_groups()` functions could also be used for `guest` and `operator` level users.  We've talked opening up guest access to sysrepo, relying fully on NACM, in which case we could create a new group `sysrepo` for `/dev/shm/*` files.
=> confd: ensure admin users have full access to vtysh

test/case/ietf_interfaces/bridge_vlan/bridge_vlan.adoc, test/case/ietf_interfaces/lag_basic/lag_basic.adoc, test/case/ietf_interfaces/lag_failure/lag_failure.adoc, test/case/infix_dhcp/server_subnets/server_subnets.adoc, test/case/use_case/ospf_container/ospf_container.adoc
{topdoc} is needed for asciidoctor to find the image during test report generation.
=> test: fix image paths in test specifications

package/finit/finit.hash, package/finit/finit.mk
Final bump from 4.10-rc2 -> 4.10 GA.  For the full ChangeLog, see https://github.com/troglobit/finit/releases/tag/4.10
Only change between rc2 and the GA is https://github.com/troglobit/finit/commit/1691ebb2925b985356d3ba03c672990f2cd8a4a1 which goes with the latest changes to [sysklogd v2.7.1](https://github.com/troglobit/sysklogd/releases/tag/v2.7.1), which will hopefully make it to Buildroot 2025.02.0.
=> Upgrade Finit to v4.10

test/case/ietf_interfaces/bridge_vlan/bridge_vlan.adoc, test/case/ietf_interfaces/lag_basic/lag_basic.adoc, test/case/ietf_interfaces/lag_failure/lag_failure.adoc, test/case/infix_dhcp/server_subnets/server_subnets.adoc, test/case/use_case/ospf_container/ospf_container.adoc, test/spec/generate_spec.py
{topdoc} is needed for asciidoctor to find the image during test report generation.
This is the same functional change as 02d8288863e2 but with the generation script actually updated. This was forgotten in the last commit.
=> test: fix image paths in test specifications (again)

test/env
Make the NINEPM_PROJ_CONFIG environment variable available for 9pm inside the test env.
=> test: pass 9pm project conf to test environment

board/common/rootfs/usr/bin/dir, doc/ChangeLog.md, src/bin/copy.c, src/bin/files.c, src/klish-plugin-infix/src/infix.c
=> Fix annoying "permission denied" when saving running-config

.github/workflows/release.yml, board/common/mkdisk.sh, board/common/post-image.sh, board/common/qemu/qemu.sh, board/common/rootfs/usr/libexec/infix/init.d/30-cfg-migrate, doc/ChangeLog.md, test/env, test/templates/inc/infix-disk.mustache, test/templates/inc/infix-usb.mustache, test/templates/infix-bios-x86_64.mustache, test/templates/infix-kernel-x86_64.mustache, test/templates/infix-x86_64.mustache, test/test.mk, test/virt/quad/topology.dot.in
Changed image type from RAW to qcow2
Also:
* Fix symlink in release packages, this fix #1002
* Add qcow2 disk image as release artifact
* Fix logging issue when try to migrate but there is no /cfg/startup-config.cfg (factory reset)
=> Change type of disk image

src/confd/bin/migrate
Allows a user to run the migrate script off-target.
Example of running it locally:
`./migrate -e -s ../share/migrate/ ~/old-factory-config.cfg` 
=> Run migrate script locally

src/confd/bin/migrate
The version migrate looks for is "version" in:
```
"infix-meta:meta": {
"version": "1.5"
},
```
Prior to this patch migrate actually wrote:
```
"infix-meta:meta": {
"infix-meta:version": "1.5"
},
```
=> confd: remove prefix from version leaf in migrate

utils/srload
The original syntax did not work and the initial intention, that root is always required is also false.
=> srload: Cleanup when running outside buildtree

doc/ChangeLog.md
2025.02.1, released April 22nd, 2025
Changes with potentially large impact:
- gstreamer1 and related packages: updated from 1.22.x to 1.24.x. 1.22.x was already EOL when Buildroot 2025.02 was released, so GStreamer should really already have been udpated to 1.24.x. This update was needed to fix a lot of vulnerabilities.
- frr: updated from 9.1.3 to 10.3. Version 9 is no longer maintained upstream, and not in any distro either. This update was needed to fix a vulernability.  <-- REVERTED IN INFIX
Important / security related fixes:
- libmodsecurity: CVE-2025-27110.
- tinyxml2: CVE-2024-50615.
- xserver_xorg-server & xwayland: CVE-2024-9632, CVE-2025-26594, CVE-2025-26595, CVE-2025-26596, CVE-2025-26597,  CVE-2025-26598, CVE-2025-26599, CVE-2025-26600, CVE-2025-26601.
- exim: …
=> Upgrade buildroot to 2025.02.1 (LTS)

board/common/rootfs/usr/libexec/infix/has-quirk, board/common/rootfs/usr/libexec/infix/init.d/25-mqprio, src/board/freescale-imx8mp-evk/rootfs/usr/share/product/fsl,imx8mp-evk/etc/product/interface-quirks.json
The kernel just hang, adding a quirk for it.
=> imx8mp-evk: Disable mqprio for eth1

doc/ChangeLog.md, doc/boot.md, doc/cli/upgrade.md, doc/management.md, doc/system.md
- Add section on upgrading/downgrading and boot-order to system.md
- Add or update references on upgrading from other pages
- boot.md (update ref)
- cli/upgrade.md (add ref)
- management.md (add ref)
Fixes #1009
=>  Doc upgrade/downgrade policy

test/case/infix_containers/Readme.adoc, test/case/infix_containers/container_host_commands/test.py, test/case/infix_containers/container_host_commands/topology.dot, test/case/infix_containers/infix_containers.yaml
Add a test to verify a container on Infix can execute commands on the host by mounting a script to `/etc/rc.local` with proper permissions. The test confirms host `hostname` change using `nsenter` from inside a privileged container.
=> Verify Host Command Execution from Container

utils/ixbin
```
usage: ixbin COMMAND [ARGS...]
Update contents of Infix images
Commands:
unpack PKG KEY-DIR DIR
Unpack the RAUC bundle PKG and the root filesystem contained in
it, using the keys stored in KEY-DIR, and store the results in
DIR.
pack DIR [KEY-DIR] PKG
Repackage the (possibly modified) root filesystem in DIR, updating
all signatures as necessary using the keys stored in KEY-DIR (or
the keys used to unpack the bundle, if not specified) and store
the resulting bundle in PKG.
exec DIR COMMAND [ARGS...]
Run COMMAND, possibly with ARGS, from the root of the filesystem
in DIR, inside of a fakeroot context that allows otherwise
privileged operations such as ownership modifications.
help
Show this message and exit.
Key directories:
KEY-DIR arguments must reference a directory that contains the …
```
=> ixbin: Add util script to update image contents

.github/workflows/build.yml, .github/workflows/publish.yml, .github/workflows/test.yml, .github/workflows/trigger.yml
This PR redesigns the existing github build and test workflow to support workflow calls.
Main changes:
* Add workflow calls.
* Split build.yml into build.yml and test.yml.
* Add a self trigger to run build and test on push and PR.
* Increase parameterisation.
A Spin of Infix can now use workflow calls to run Infix build and test directly. This means an Infix Spin doesn't have to duplicate or create there own github workflow for building and testing.
Here's an example of how that might look  (pseudo):
```
name: Infix SpinX CI
on:
pull_request:
types: [opened, synchronize, reopened, labeled]
...
jobs:
build-infix-x86_64:
uses: kernelkit/infix/.github/workflows/build.yml@main
with:
name: "Infix-SpinX"
target: "x86_64"
infix_repo: "kernelkit/infix"
test-infix-x86_64:
needs: build-infix-x86_64 …
```
=> Redesign CI to use workflow calls

doc/developers-guide.md
=> Document process about upgrade buildroot and kernel

.github/workflows/build.yml
=> .github: workflow dispatch fixes

test/.env, test/docker/pip-requirements.txt
Fix dependabot CVE-2024-47081 Moderate severity warning in Infamy container.
| Dependency |  Version | Upgrade to |
|-----|--|--|
| requests  |    < 2.32.4 | ~> 2.32.4 |
=> Fix dependabot moderate CVE warning in Infamy container

board/common/rootfs/usr/sbin/container, doc/ChangeLog.md
Previously, upgrading Podman containers with the same tag left behind dangling images, causing overlay storage to grow and fill disk space.
This change ensures dangling images are cleaned up using podman image prune. The command is run without -a, so only unreferenced images are removed. This provides safe cleanup while preventing unnecessary overlay growth.
Fixes #1098
=> containers: prune dangling images

.github/workflows/build.yml, .github/workflows/generic-x86-build.yml, .github/workflows/publish.yml, .github/workflows/test.yml, .github/workflows/trigger.yml
* Replace artifacts
* Re-introduce ci:main tag
* Build full version on main branch
=> CI: Various small improvments

board/aarch64/rootfs/etc/rauc/system.conf, board/common/rootfs/etc/finit.d/available/rauc.conf, board/riscv64/rootfs/etc/rauc/system.conf, board/x86_64/rootfs/etc/rauc/system.conf, doc/ChangeLog.md, src/confd/src/infix-system-software.c
- #1080 
- Two new optional arguments to `install-bundle` RPC
- `verify-certificate` — weather to verify bundle certificate at install, default: `True`
- `verify-compatible` — weather to verify if bundle is compatible, default: `True`
- Drop redirect of rauc console events (ANSI color coded) in favor of dedicated JSON event log
=> Rauc integration fixes

test/infamy/env.py, test/infamy/restconf.py, test/infamy/tap.py
A mix of test framework fixes and improvements extracted from the firewall branch for separate review.
=> Mix of test framework fixes and improvements

test/case/ietf_routing/ospf_basic/test.adoc, test/case/ietf_routing/ospf_basic/test.py, test/case/ietf_routing/ospf_basic/topology.dot, test/case/ietf_routing/ospf_basic/topology.svg, test/infamy/route.py
Extend OSPF basic with a regression test for issue #1169
=> Verify OSPF neighbors in setup with non-OSPF interface

.github/workflows/trigger.yml
When building from a PR, potentially an older maintenance branch, we should not upload the built artifacts to the `latest` tag.
=> Only publish to latest release from main branch
