doc/discovery.md
Adding rudimentary information on discovery of Infix units and Infix Discovery services.
Is title ok?
Should we add links/references or more info on mDNS/DNS-SD or SSDP? I have not even spelled out the acronyms ...
But hopefully this is a good start. :-)
=> Infix doc mgmt

package/confd/sysrepo.conf, src/confd/src/confd/dagger.c, src/confd/src/confd/dagger.h, src/confd/src/confd/ietf-interfaces.c, test/case/infix_interfaces/bridge_basic.py, test/infamy/netconf.py
Cleanup and prep for bridge native VLAN support.  Most important fix is addition of missing `nomaster` support for bridge links, as well as diff support for moving ports between bridges.
=> Misc. bridge fixes

test/case/ietf_interfaces/all.yaml, test/case/ietf_interfaces/iface_status.py, test/infamy/iface.py
- Added "iface.py" module for interface related functions(checks)
- Added a test case for interface existence check
- Added test cases for interface parameters "if-index" and "oper-status" check
=> test/case: Add interface test

test/docker/pip-requirements.txt, test/env
Added **passlib** module for password hash purposes
=> "test/docker: add passlib to docker image"

src/statd/statd.c
Add tx and rx bytes as YANG out-octets and in-octets.
=> statd: add tx/rx counters to iface operational data

src/klish-plugin-infix/xml/infix.xml
Prior to this patch the indentation was a mix of tabs and spaces. Now use 2 spaces as indentation.
=> klish-plugin-infix: fix indentation in infix.xml

.github/workflows/sync-fork.yml
=> Fix #107: auto-sync forks every day 2:42 UTC or on dispatch

.github/workflows/regression.yml, board/x86_64/board.mk, test/case/all-unit.yaml, test/case/cli_pretty/run.sh
This currently includes cli-pretty tests. It could be executed separately to clarify test results in github actions. This commit includes it in the main test execution. The most important thing is that it's executed.
=> test: add top level unit test suite

doc/networking.md
Improved "show interfaces" information is now
reflected in IP address examples
- source info added
- IPv6 addresses shown
Also added an example with IPv6 privacy for stateless autoconfig
=> Doc: Updating IP address assignment examples

src/statd/statd.c
Xlate IFF_UP flag to admin-status: up/down.  We do not support any 'testing' mode (yet) in Infix.
=> statd: add support for ietf-interfaces/interface/admin-status

.github/workflows/build.yml, .github/workflows/regression.yml, .github/workflows/sync-fork.yml, Config.in, board/common/post-build.sh, board/common/post-image.sh, package/confd/confd.conf, src/confd/bin/.confdrc, src/confd/bin/gen-interfaces, src/confd/confdrc
Misc. branding and override support for br2-externals.
=> Branding, customization, and various fixes

board/common/rootfs/bin/yorn, src/confd/src/Makefile.am, src/confd/src/core.c, src/confd/src/core.h, src/confd/src/ietf-factory-default.c, src/klish-plugin-infix/xml/infix.xml
=> ietf-factory-default: Implement factory reset

board/common/rootfs/lib/infix/mnt, src/confd/bin/gen-interfaces
- IPv6 support for port interfaces in gen-interfaces
- Extend factory-reset check and function
=> Misc fixes

doc/networking.md
=> Update documentation for VLAN configuration

board/netconf/rootfs/lib/infix/cli-pretty, board/netconf/rootfs/lib/infix/yanger
Add `speed` and `duplex` to operational data store and print them in CLI
=> Statd add speed and duplex

README.md, src/.clang-format, src/confd/src/ietf-interfaces.c, src/confd/src/ietf-routing.c, src/confd/src/ietf-system.c, src/statd/statd.c
Lots of small fixes in the src directory due to the Coverity findings, please have a look at your respective parts.  Most of it is pretty straight-forward logical mistakes.
=> Coverity fixes

board/common/Config.in, board/common/rootfs/etc/finit.d/available/rauc.conf, board/common/rootfs/etc/syslog.d/rauc.conf, board/netconf/rootfs/lib/infix/cli-pretty, doc/boot.md, doc/cli/introduction.md, doc/cli/tutorial.md, patches/rauc/1.8/0001-src-bundle-enable-tftp-protocol.patch, patches/rauc/1.8/0002-src-main-add-optional-syslog-support.patch, src/klish-plugin-infix/xml/infix.xml
Add basic '`upgrade URI` and `show firmware` commands to CLI.
=> CLI upgrade command

package/greenpak-programmer/greenpak-programmer.hash, package/greenpak-programmer/greenpak-programmer.mk
adds verification of programmed NVMEM / EEPROM
=> Bump greenpak-programmer to v1.2

test/docker/Dockerfile, test/env
Needed by upcoming unit tests.
=> test/docker: Add jq to docker

.gitmodules, board/x86_64/board.mk, test/env
=> Relocate qeneth and 9pm submodules to test/

board/netconf/rootfs/libexec/infix/ospf-status, board/netconf/rootfs/libexec/infix/yanger, doc/networking.md, src/confd/src/ietf-routing.c, src/confd/yang/infix-routing@2023-11-23.yang, src/libsrx/src/lyx.c, src/libsrx/src/lyx.h, test/infamy/netns.py
Add more operational support:
* Neighbors
* OSPF Routing table
* Router ID
Add NSSA/Stub area support
=> Improve OSPF support

board/common/rootfs/sbin/dagger, package/finit/finit.hash, package/finit/finit.mk
For details, see https://github.com/troglobit/finit/releases/tag/4.7
=> Bump finit and LOG_PID in dagger

board/common/qemu/qemu.sh, board/netconf/rootfs/libexec/infix/yanger, src/.clang-format, src/confd/bin/bootstrap, src/confd/yang/iana-hardware@2018-03-13.yang, src/confd/yang/ietf-hardware@2018-03-13.yang, src/confd/yang/infix-hardware@2024-01-18.yang, src/statd/statd.c
* Fix coding style in statd.
* Reduce code duplication in statd.
* Represent the VPD as a component in ietf-hardware
=> add ietf hardware

src/confd/yang/infix-dhcp-client@2023-05-22.yang, src/confd/yang/infix-if-bridge@2023-12-02.yang, src/confd/yang/infix-if-veth@2023-06-05.yang, src/confd/yang/infix-if-vlan@2023-10-25.yang, src/confd/yang/infix-interfaces@2023-09-19.yang, src/confd/yang/infix-ip@2023-09-14.yang, src/confd/yang/infix-routing@2024-01-09.yang, src/confd/yang/infix-system-software@2023-06-27.yang, src/confd/yang/infix-system@2023-10-19.yang
Align indentation in all infix yang models to be 2 spaces.
=> Fix infix yang indentation

test/case/all.yaml, test/case/misc/all.yaml, test/case/misc/operational_all.py, test/infamy/netconf.py
=> Add test to se that it is possible to get all operational data

board/common/rootfs/usr/share/udhcpc/default.script, src/confd/bin/bootstrap, src/confd/src/infix-dhcp.c, src/confd/yang/infix-dhcp-client@2023-05-22.yang, src/confd/yang/infix-dhcp-client@2024-01-30.yang
This PR address the problems reported in issues #278 and #283.
=> DHCP client fixes

.github/workflows/build.yml, .github/workflows/coverity.yml, README.md, src/confd/src/infix-dhcp.c, src/statd/statd.c
Also some minor changes:
* Update github actions (from v3 to v4), v3 is deprecated
* Fix coverity bugs
* Add discord badge to README
=> Run coverity each day

board/netconf/rootfs/libexec/infix/yanger
Various refactoring and pylint fixes to yanger. There should be no functional change in this PR. 
=> Cosmetic cleanup of yanger

test/case/ietf_routing/ospf_basic.py, test/case/ietf_routing/ospf_multiarea.py, test/case/ietf_routing/ospf_unnumbered_interface.py
This since when running the test in the cloud with github supplied runner, everthing sometimes gets really slow.
- [x ] Refactoring (please detail in commit messages)
=> test: Increase timeouts for OSPF tests

src/confd/bin/bootstrap, src/confd/yang/infix-if-type@2024-01-29.yang
=> Update revision for infix-if-type

src/klish-plugin-infix/xml/infix.xml, src/statd/cli-pretty, test/case/cli/run.sh, test/case/cli_pretty/all.yaml, test/case/cli_pretty/run.sh
Instead focus on the task to do 'show hardware', 'show interfaces' and more, this to make it more logical.
=> cli-pretty: Refactor to not take model as argument

.github/workflows/regression.yml
=> Change to self-hosted runner

README.md, doc/README.md, doc/cli/text-editor.md, doc/eth-counters.md, doc/hardware.md, doc/license.md, doc/networking.md, doc/scripting.md, doc/system.md, doc/testing.md, doc/variant.md, package/klish-plugin-infix/Config.in
=> Misc documentation fixes and disable shell command in CLI

doc/container.md, doc/qos.md
Start to document default QoS policy of mv88e6xxx
=> doc/qos: Start to document default QoS policy of mv88e6xxx

.github/workflows/regression.yml
This reverts commit b2fef1585f6f71f48cf26ba8c1941bd81567c74e.
=> Revert "Change to self-hosted runner"

doc/testing.md, test/case/all.yaml, test/case/meta/play.py, test/case/meta/reproducible.py, test/case/meta/wait.py, test/env, test/infamy/env.py, test/infamy/topology.py
- Present the topologies to networkx as multigraphs, rather than expaning each port of the record shape as a separate node.
- Create a topology mapping by locating a subgraph monomorphism of the logical topology in the physical ditto.
This cuts down the time of finding a mapping by several orders of magnitude. Example:
Before:
```
time python3 test/infamy/topology.py \
test/virt/quad/topology.dot.in \
test/infamy/topologies/ring-4-duts.dot >/dev/null
real    13m1,213s
user    13m0,112s
sys     0m0,732s
```
After:
```
time python3 test/infamy/topology.py \
test/virt/quad/topology.dot.in \
test/infamy/topologies/ring-4-duts.dot >/dev/null
real    0m0,153s
user    0m0,128s
sys     0m0,024s
```
Also, optionally use deterministic topology mappings.
Due to the salting being applied to Python's …
=> test: Improve efficiency of logical to physical topology matching

doc/ChangeLog.md, package/confd/confd.conf, package/statd/statd.conf, patches/sysrepo/2.2.105/0001-sysrepo-plugind-add-support-for-running-in-foregroun.patch, patches/sysrepo/2.2.105/0002-Refactor-_sr_install_modules-to-use-ly_ctx_load_modu.patch, patches/sysrepo/2.2.105/0003-Add-support-for-loading-etc-sysrepo-factory-default.patch, patches/sysrepo/2.2.105/0004-sysrepoctl-add-support-for-Cfactory-d-running.patch, patches/sysrepo/2.2.105/0005-Allow-SR_EV_DONE-to-return-any-error-to-sysrepocfg.patch, src/confd/bin/bootstrap, src/confd/bin/load, src/confd/src/cni.c, src/confd/src/ietf-hardware.c, src/confd/src/ietf-interfaces.c, src/confd/src/ietf-routing.c, src/confd/src/ietf-system.c, src/confd/src/infix-containers.c, src/confd/src/infix-dhcp.c, src/confd/src/infix-services.c, src/libsrx/src/common.h, src/statd/statd.c
This PR primarily deals with the following critical issues:
- #428 
- #429 
During the investigation several other minor, and major, issues were also found and fixed.  Please see each respective commit for details.
=> Login regression and segfault fixes

test/case/ietf_routing/ospf_basic.py, test/case/ietf_routing/ospf_multiarea.py, test/case/ietf_routing/ospf_unnumbered_interface.py, test/case/ietf_routing/static_routing.py, test/case/infix_interfaces/igmp_vlan.py
Test refactor, run things that benefits of running in parallel, in parallel.
Test has been run on hardware with result:
<pre>
`-- s 0001-all.yaml
|-- o 0002-reproducible.py
|-- o 0003-wait.py
|-- o 0004-Misc tests
|   `-- o 0005-operational_all.py
|-- o 0006-ietf-system
|   |-- o 0007-hostname.py
|   |-- o 0008-add_delete_user.py
|   |-- o 0009-timezone.py
|   `-- o 0010-timezone_utc_offset.py
|-- o 0011-ietf-interfaces
|   |-- o 0012-vlan_ping.py
|   |-- o 0013-ipv4_address.py
|   |-- o 0014-iface_phys_address.py
|   |-- o 0015-iface_status.py
|   `-- o 0016-routing_basic.py
|-- o 0017-infix-interfaces
|   |-- o 0018-bridge_basic.py
|   |-- o 0019-bridge_veth.py
|   |-- o 0020-dual_bridge.py
|   |-- o 0021-bridge_vlan.py
|   |-- o 0022-ipv4_autoconf.py
|   |-- o …
=> Refactor ietf-routing tests and igmp_vlan

board/common/post-image.sh
cp: cannot stat '/home/lazzer/Documents/addiva/infix/board/common/rootfs/bin/onieprom': No such file or directory
=> Fix regression when merge /usr

README.md, doc/testing.md, src/confd/share/failure.d/10-infix-services.json, src/confd/share/failure.d/Makefile.am, src/confd/src/infix-services.c
Release announcement available from the Buildroot list:
https://lore.kernel.org/buildroot/87v803gwip.fsf@dell.be.48ers.dk/T/#u
=> buildroot: bump to 2024.02.5

board/common/post-build.sh, doc/ChangeLog.md, doc/syslog.md, patches/sysrepo/2.10.1/0007-Introduce-new-log-level-SEC-for-audit-trails.patch, patches/sysrepo/2.10.1/0008-Add-audit-trail-for-high-priority-system-changes.patch, patches/sysrepo/2.10.1/0009-On-error-in-sr_shmsub_listen_thread-exit-process.patch, src/confd/src/core.c, src/confd/src/ietf-syslog.c, src/confd/src/ietf-system.c, src/libsrx/src/common.h, src/statd/statd.c
=> Log facility fixes

board/common/rootfs/usr/bin/doas, doc/ChangeLog.md, src/klish-plugin-infix/xml/infix.xml
- Fix shellcheck issues with `doas`
- Fix #601 
=> Fix CLI `show ospf` permissions for admin group users

.github/workflows/build.yml, .github/workflows/release.yml
Also include the test specification in release tarballs.
=> Build test specification on build

test/.env, test/docker/pip-requirements.txt, test/infamy/netconf.py
Refactor NETCONF functions (get_data) to accommodate the upgrade
in the netconf_client library within the Docker container image.
=> Upgrade NETCONF Client from 2.2.0 to 3.1.1

src/confd/src/ietf-interfaces.c
Dagger did delete of the VLAN after it had configured it. Resulting in that the new VLAN configuration was lost.
This will first delete all untagged/tagged ports that should be removed, when they are removed, add the new or changed ports.
This fix #676 
=> Do not delete VLAN when change a port from tagged to untagged

doc/container.md
Fixing some URLs and typos
None
=> Doc: minor fixes to container doc

.github/workflows/add-issue-to-project.yml
=> CI: Use specific token when calling add to project

doc/ChangeLog.md, package/klish/Config.in
=> Add missing copy and erase commands to CLI

doc/networking.md, doc/system.md
NTP functionality has been thoroughly verified and the proper documentation is added on:
- Configuring NTP
- Verifying NTP Status
- Verifying NTP Sources
=> Update system.md by adding NTP details

test/case/ietf_routing/static_routing/test.py, test/case/ietf_system/timezone/test.py, test/case/ietf_system/timezone_utc_offset/test.py, test/infamy/netconf.py, test/infamy/restconf.py, test/infamy/transport.py
When using put_config_dicts, set hostname if not set.
Also convert some tests to use put_config_dicts instead of put_config_dict
=> Set hostname in infamy

doc/ChangeLog.md, doc/networking.md
Doc covering
- redistribute static/connected
- distribute-default-route [always]
- explicit-router-id
=> Add rudimentary documentation on global OSPF settings

.github/CHECKLIST.md, .github/workflows/release.yml
- Create new discussion only for GA releases
- Remember to push tags
=> Minor release engineering fixes

test/case/ietf_interfaces/bridge_vlan_separation/Readme.adoc, test/case/ietf_interfaces/bridge_vlan_separation/test.py
Only check for the broadcast sent.
And add more test specification steps
=> test: bridge_vlan_separation: Make test more robust

doc/ChangeLog.md
=> Final ChangeLog updates for v24.11.1

test/case/all.yaml, test/case/meta/reproducible.py, test/infamy/netconf.py, test/infamy/restconf.py, test/infamy/transport.py
Make sure that we keep a record of the versions and boot source used by all devices under test when running the full suite - in case we ever suspect that there is a mismatch between the intended test image and the actual one.
=> test: reproducible: Log software versions

test/.env, test/case/ietf_interfaces/static_multicast_filters/Readme.adoc, test/case/ietf_interfaces/static_multicast_filters/test.py, test/docker/pip-requirements.txt, test/infamy/multicast.py
This PR enhances the existing "static-multicast-filters" test by adding verification for MAC multicast functionality.
=> Verify MAC Multicast

src/confd/src/ietf-system.c
=> confd: Fix memory leaks in ietf-system.c

test/.env, test/docker/Dockerfile
Intended to be used when fetching version information for the test report.
=> test: add git to docker container

src/confd/src/ietf-keystore.c, src/confd/src/ietf-syslog.c, test/case/ietf_syslog/basic/test.py, test/case/ietf_syslog/remote/test.py, utils/generate-defconfig.sh
Also minor fixes, refactor syslog tests to use put_config_dicts and fix a minor bug in generate_defconfig script.
=> Fix memory leaks

.github/workflows/build.yml
=> Fix history in GitHub actions

utils/gh-dl-artifact.sh
When brandlabling this may not be infix-, rather vendor-,
use *- for now.
=> utils/gh-dl-artifact: Accept any prefix for tar.gz package

doc/eth-counters.md
Update documentation for YANG to Ethtool counter mappings.
[skip ci]
Fixes #770
=> Update documentation for YANG to Ethtool counter mappings

doc/developers-guide.md, doc/test-arch.md, doc/testing.md
This PR contains documentation update on Infix development processes.
=> Update Processes Documentation

.github/SECURITY.md
Add a new security policy in SECURITY.md. This file is interpreted by Github.
Fixes: #924 
=> .github: add security policy (SECURITY.md)

board/common/rootfs/etc/sysctl.d/ipv6.conf, doc/ChangeLog.md, doc/networking.md, src/confd/src/ietf-interfaces.c
=> Disable IPv6 forwarding by default

test/case/ietf_interfaces/bridge.yaml, test/case/ietf_interfaces/bridge_vlan/bridge_vlan.adoc, test/case/ietf_interfaces/ietf_interfaces.yaml, test/case/ietf_interfaces/igmp.yaml, test/case/ietf_interfaces/lag.yaml, test/case/ietf_interfaces/lag_basic/lag_basic.adoc, test/case/ietf_interfaces/lag_failure/lag_failure.adoc, test/case/ietf_interfaces/tunnels.yaml, test/case/infix_dhcp/dhcp_client.yaml, test/case/infix_dhcp/dhcp_server.yaml, test/case/infix_dhcp/infix_dhcp.yaml, test/case/infix_dhcp/server_subnets/server_subnets.adoc, test/case/infix_services/infix_services.yaml, test/case/infix_services/lldp.yaml, test/case/infix_services/mdns.yaml, test/case/infix_services/ssh.yaml, test/case/use_case/ospf_container/ospf_container.adoc
Split e.g. interfaces to multiple sub suites.
This fix #960
=> Split test to suites

README.md
Prominent location for our most prominent sponsor.
=> Add sponsor section to README

doc/ChangeLog.md
=> doc: update ChangeLog

.github/workflows/build.yml, .github/workflows/release.yml
=> .github: preserve symlinks in tarballs

board/common/rootfs/etc/finit.d/available/ttyd.conf, board/common/rootfs/usr/sbin/container, doc/ChangeLog.md, package/finit/finit.hash, package/finit/finit.mk
This PR fixes two nasty bugs:
- #980 
- #990 
=> Fix reboot when containers are in setup state

doc/ChangeLog.md
=> Bump version for v25.03.0 GA

doc/developers-guide.md, doc/netboot.md
New HowTo for network booting when developing with Infix.
=> Netboot HowTo

package/finit/finit.hash, package/finit/finit.mk
- Improve notify:s6 readiness compatibility
- Update `runparts` usage text
- Fix variable overloading in urandom plugin
- Fix buffer overwrite in urandom plugin
=> Bump Finit to v4.12

doc/ChangeLog.md
=> Update changelog for v25.04.0

doc/ChangeLog.md, src/confd/yang/confd/infix-if-lag.yang
Fixes #1031
Correct description (help text) for LACP modes in infix-if-lag.yang
=> Correct Description for LAG LACP Modes

.github/workflows/build.yml
This to get quick turnaround development -> test when doing PRs main branch builds and release builds are still build sequentially.
=> Use massive parallel in workflow for PRs

doc/ChangeLog.md
=> Update changelog for v25.05.0

doc/ChangeLog.md
Updating changelog for Infix v25.05.1
=> Update changelog for Infix v25.05.1

doc/ChangeLog.md
=> Bump buildroot to 2025.02.4 (LTS)

doc/ChangeLog.md
Setting date for release and updating diff references at the end
=> Update Changelog for Infix v25.06.0

doc/ChangeLog.md
This PR exists mainly to trigger GH-moon tests.
=> doc: update changelog date for v25.06

doc/ChangeLog.md, doc/scripting-netconf.md, doc/scripting-restconf.md, mkdocs.yml
Fixes the following issue, but also adds a similar document for scripting with NETCONF.  Which was looooooong overdue.
- #1156
=> doc: update scripting with restconf and add similar for netconf
